[program:tess_sector]
command=/usr/bin/env python services/tess_sector/tess_sector.py %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/tess_sector.log
redirect_stderr=true
