---
parser: "babel-eslint"
env:
  browser: true
  es6: true
plugins: [
  "import",
  "react",
  "react-hooks"
]
extends: [
  "airbnb",
  "plugin:react/recommended"
]
settings:
  import/resolver:
    node: {}
    webpack:
      config: webpack.config.js
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  camelcase: off
  comma-dangle: [1, only-multiline]
  no-else-return: 0
  no-param-reassign: 0
  quotes: 0
  space-infix-ops: 0
  no-underscore-dangle: [2, {"allowAfterThis": true}]
  object-curly-newline: [2, {"consistent": true}]
  operator-linebreak: [1, after]
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/control-has-associated-label: 0
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
