---
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    # Must match webpack.config.js
    presets: ["@babel/preset-env", "@babel/preset-react"]
env:
  browser: true
plugins: ["import", "react", "react-hooks"]
extends: ["airbnb", "plugin:react/recommended", "prettier"]
settings:
  import/resolver:
    node: {}
    webpack:
      config: webpack.config.js
  react:
    version: detect
rules:
  camelcase: off
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/control-has-associated-label: 0
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  react/jsx-wrap-multilines: 0
  react/jsx-one-expression-per-line: 0
  react/jsx-props-no-spreading: 0
  no-param-reassign: 0
  react/jsx-curly-newline: 0
