name: Reusable Cache Workflow
inputs:
  key-prefix:
    description: Cache key prefix
    default: "pr"

on:
  workflow_call:

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v5
      with:
        path: |
          ~/.npm
        key: ${{ inputs.key-prefix }}-${{ runner.os }}-npm-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ inputs.key-prefix }}-${{ runner.os }}-npm-

    - uses: actions/cache@v5
      with:
        path: |
          ~/.cache/uv
        key: ${{ inputs.key-prefix }}-${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
        restore-keys: |
          ${{ inputs.key-prefix }}-${{ runner.os }}-uv-

    # caching dustmap & sncosmo files is dependent on their corresponding
    # python package versions, so we use that as the cache key
    - uses: actions/cache@v5
      with:
        path: |
          persistentdata/dustmap/sfd
        key: ${{ inputs.key-prefix }}-${{ runner.os }}-dustmap-${{ hashFiles('uv.lock') }}
        restore-keys: |
          ${{ inputs.key-prefix }}-${{ runner.os }}-dustmap-

    - uses: actions/cache@v5
      with:
        path: |
          ~/.astropy/cache/sncosmo/bandpasses
        key: ${{ inputs.key-prefix }}-${{ runner.os }}-sncosmo-${{ hashFiles('uv.lock') }}
        restore-keys: |
          ${{ inputs.key-prefix }}-${{ runner.os }}-sncosmo-
