[program:ep_service]
command=/usr/bin/env python services/ep_service/ep_service.py %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/ep_service.log
redirect_stderr=true
