[program:broker_ingest]
command=/usr/bin/env python services/broker_ingest/broker_ingest.py %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/broker_ingest.log
redirect_stderr=true
autorestart=true
startretries=10
