[program:gcn_crossmatch]
command=/usr/bin/env python services/gcn_crossmatch/gcn_crossmatch.py %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/gcn_crossmatch.log
redirect_stderr=true
