"""Add release to public source pages

Revision ID: 05bda3fff04d
Revises: ce87ed8ca4b5
Create Date: 2024-07-11 09:41:11.902439

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bda3fff04d'
down_revision = '94f87495c701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'publicreleases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('link_name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('is_visible', sa.Boolean(), nullable=False),
        sa.Column('options', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('link_name'),
    )
    op.create_index(
        op.f('ix_publicreleases_created_at'),
        'publicreleases',
        ['created_at'],
        unique=False,
    )
    op.create_table(
        'group_public_releases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('publicrelease_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['publicrelease_id'], ['publicreleases.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'group_public_releases_forward_ind',
        'group_public_releases',
        ['group_id', 'publicrelease_id'],
        unique=True,
    )
    op.create_index(
        'group_public_releases_reverse_ind',
        'group_public_releases',
        ['publicrelease_id', 'group_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_group_public_releases_created_at'),
        'group_public_releases',
        ['created_at'],
        unique=False,
    )
    op.add_column(
        'publicsourcepages', sa.Column('release_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, 'publicsourcepages', 'publicreleases', ['release_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publicsourcepages', type_='foreignkey')
    op.drop_column('publicsourcepages', 'release_id')
    op.drop_index(
        op.f('ix_group_public_releases_created_at'), table_name='group_public_releases'
    )
    op.drop_index(
        'group_public_releases_reverse_ind', table_name='group_public_releases'
    )
    op.drop_index(
        'group_public_releases_forward_ind', table_name='group_public_releases'
    )
    op.drop_table('group_public_releases')
    op.drop_index(op.f('ix_publicreleases_created_at'), table_name='publicreleases')
    op.drop_table('publicreleases')
    # ### end Alembic commands ###
