"""update to photometric series for plotting

Revision ID: 06aa146dea7a
Revises: e268e17ca352
Create Date: 2023-03-10 11:29:24.501251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06aa146dea7a'
down_revision = 'a8318144625d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'photometric_series', sa.Column('limiting_mag', sa.Float(), nullable=False)
    )
    op.add_column(
        'photometric_series', sa.Column('ref_flux', sa.Float(), nullable=True)
    )
    op.add_column(
        'photometric_series', sa.Column('ref_fluxerr', sa.Float(), nullable=True)
    )
    op.drop_index('ix_photometric_series_magref', table_name='photometric_series')
    op.create_index(
        op.f('ix_photometric_series_limiting_mag'),
        'photometric_series',
        ['limiting_mag'],
        unique=False,
    )
    op.create_index(
        op.f('ix_photometric_series_ref_flux'),
        'photometric_series',
        ['ref_flux'],
        unique=False,
    )
    op.drop_column('photometric_series', 'magref')
    op.drop_column('photometric_series', 'magref_unc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'photometric_series',
        sa.Column(
            'magref_unc',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'photometric_series',
        sa.Column(
            'magref',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        op.f('ix_photometric_series_ref_flux'), table_name='photometric_series'
    )
    op.drop_index(
        op.f('ix_photometric_series_limiting_mag'), table_name='photometric_series'
    )
    op.create_index(
        'ix_photometric_series_magref', 'photometric_series', ['magref'], unique=False
    )
    op.drop_column('photometric_series', 'ref_fluxerr')
    op.drop_column('photometric_series', 'ref_flux')
    op.drop_column('photometric_series', 'limiting_mag')
    # ### end Alembic commands ###
