"""TNS robot auto submission migration

Revision ID: 0a4e98db3bcb
Revises: 6f23bbeb119d
Create Date: 2023-05-26 17:58:48.160706

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0a4e98db3bcb"
down_revision = "6f23bbeb119d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tnsrobots",
        sa.Column(
            "auto_report_group_ids",
            postgresql.ARRAY(sa.Integer()),
            nullable=True,
            comment="List of group IDs to report from",
        ),
    )
    op.add_column("tnsrobots", sa.Column("auto_reporters", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tnsrobots", "auto_reporters")
    op.drop_column("tnsrobots", "auto_report_group_ids")
    # ### end Alembic commands ###
