"""add gin index obj model

Revision ID: 0bf37205a0bb
Revises: 9f2a7c3e1b45
Create Date: 2026-01-12 10:58:53.493832

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "0bf37205a0bb"
down_revision = "9f2a7c3e1b45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure pg_trgm extension is available for trigram indexing
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # Create an IMMUTABLE function to convert alias array to lowercase string
    # This is required because PostgreSQL needs to know the function is stable
    # for use in functional indexes
    op.execute(
        """
        CREATE OR REPLACE FUNCTION objs_alias_to_lower_text(alias text[])
        RETURNS text
        LANGUAGE sql
        IMMUTABLE
        AS $$
            SELECT lower(array_to_string(alias, ' '))
        $$;
        """
    )

    # Create GIN trigram index using the immutable function
    # This significantly improves performance for LIKE queries on aliases
    op.create_index(
        "idx_objs_alias_gin_trgm",
        "objs",
        [sa.text("objs_alias_to_lower_text(alias)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"objs_alias_to_lower_text(alias)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the GIN trigram index
    op.drop_index("idx_objs_alias_gin_trgm", table_name="objs")

    # Drop the immutable function
    op.execute("DROP FUNCTION IF EXISTS objs_alias_to_lower_text(text[]);")
    # ### end Alembic commands ###
