"""add gin index obj model

Revision ID: 0bf37205a0bb
Revises: 9f2a7c3e1b45
Create Date: 2026-01-12 10:58:53.493832

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "0bf37205a0bb"
down_revision = "9f2a7c3e1b45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pg_trgm extension for trigram-based pattern matching
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # Create GIN index with gin_trgm_ops operator class
    op.execute("CREATE INDEX ix_objs_alias_gin ON objs USING gin (alias gin_trgm_ops)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_objs_alias_gin", table_name="objs")
    # ### end Alembic commands ###
