"""Galaxy w1/w2/w3/w4 migration

Revision ID: 0e9932f8b83e
Revises: b2aadcb864d1
Create Date: 2023-05-29 21:28:09.300603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9932f8b83e'
down_revision = 'b2aadcb864d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galaxys', sa.Column('mag_w1', sa.Float(), nullable=True))
    op.add_column('galaxys', sa.Column('mag_w2', sa.Float(), nullable=True))
    op.add_column('galaxys', sa.Column('mag_w3', sa.Float(), nullable=True))
    op.add_column('galaxys', sa.Column('mag_w4', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('galaxys', 'mag_w4')
    op.drop_column('galaxys', 'mag_w3')
    op.drop_column('galaxys', 'mag_w2')
    op.drop_column('galaxys', 'mag_w1')
    # ### end Alembic commands ###
