"""Synthetic photometry

Revision ID: 111d0c968332
Revises: 5bedad46562c
Create Date: 2022-03-30 11:46:57.907566

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "111d0c968332"
down_revision = "5bedad46562c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spectra", sa.Column("units", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spectra", "units")
    # ### end Alembic commands ###
