"""Add skymap slicing

Revision ID: 13092a80691c
Revises: 80434b53562c
Create Date: 2021-11-20 16:17:19.862052

"""
from alembic import op
import sqlalchemy as sa
import healpix_alchemy

# revision identifiers, used by Alembic.
revision = '13092a80691c'
down_revision = '80434b53562c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'localizationtiles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('localization_id', sa.Integer(), nullable=False),
        sa.Column('probdensity', sa.Float(), nullable=False),
        sa.Column('healpix', healpix_alchemy.types.Tile(), nullable=False),
        sa.ForeignKeyConstraint(
            ['localization_id'], ['localizations.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', 'healpix'),
    )
    op.create_index(
        op.f('ix_localizationtiles_created_at'),
        'localizationtiles',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_localizationtiles_healpix'),
        'localizationtiles',
        ['healpix'],
        unique=False,
        postgresql_using='spgist',
    )
    op.add_column(
        'objs', sa.Column('healpix', healpix_alchemy.types.Point(), nullable=True)
    )
    op.create_index(op.f('ix_objs_healpix'), 'objs', ['healpix'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objs_healpix'), table_name='objs')
    op.drop_column('objs', 'healpix')
    op.drop_index(
        op.f('ix_localizationtiles_healpix'),
        table_name='localizationtiles',
        postgresql_using='spgist',
    )
    op.drop_index(
        op.f('ix_localizationtiles_created_at'), table_name='localizationtiles'
    )
    op.drop_table('localizationtiles')
    # ### end Alembic commands ###
