"""goto_filters

Revision ID: 14b7c22343de
Revises: 655e76025488
Create Date: 2023-06-26 11:41:57.816883

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '14b7c22343de'
down_revision = '655e76025488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'gotob' AFTER 'desu'")
    op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'gotog' AFTER 'gotob'")
    op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'gotol' AFTER 'gotog'")
    op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'gotor' AFTER 'gotol'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
