"""executed observation table

Revision ID: 1514ec8ecf34
Revises: d61a8bea7313
Create Date: 2022-01-26 20:52:50.921815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1514ec8ecf34'
down_revision = 'd61a8bea7313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'executedobservations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('instrument_id', sa.Integer(), nullable=False),
        sa.Column('instrument_field_id', sa.Integer(), nullable=False),
        sa.Column('observation_id', sa.Integer(), nullable=False),
        sa.Column('obstime', sa.DateTime(), nullable=True),
        sa.Column('filt', sa.String(), nullable=True),
        sa.Column('exposure_time', sa.Integer(), nullable=False),
        sa.Column('airmass', sa.Float(), nullable=True),
        sa.Column('seeing', sa.Float(), nullable=True),
        sa.Column('limmag', sa.Float(), nullable=True),
        sa.Column(
            'processed_fraction',
            sa.Float(),
            nullable=False,
            comment='fraction of image processed successfully',
        ),
        sa.ForeignKeyConstraint(
            ['instrument_field_id'], ['instrumentfields.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['instrument_id'], ['instruments.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', 'instrument_field_id', 'observation_id'),
    )
    op.create_index(
        op.f('ix_executedobservations_created_at'),
        'executedobservations',
        ['created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_executedobservations_created_at'), table_name='executedobservations'
    )
    op.drop_table('executedobservations')
    # ### end Alembic commands ###
