"""Add missing indexes for Classifications table columns

Revision ID: 1562ff135257
Revises: 8f086f8c0c21
Create Date: 2021-04-08 10:44:23.982218

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1562ff135257"
down_revision = "8f086f8c0c21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_classifications_classification"),
        "classifications",
        ["classification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classifications_probability"),
        "classifications",
        ["probability"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_classifications_probability"), table_name="classifications")
    op.drop_index(
        op.f("ix_classifications_classification"), table_name="classifications"
    )
    # ### end Alembic commands ###
