"""Automatically publish source when created

Revision ID: 1593df0c0979
Revises: 0e29de8df22c
Create Date: 2025-01-21 17:42:33.178899

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1593df0c0979"
down_revision = "0e29de8df22c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publicreleases",
        sa.Column("auto_publish_enabled", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "publicsourcepages",
        sa.Column(
            "is_auto_published", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publicsourcepages", "is_auto_published")
    op.drop_column("publicreleases", "auto_publish_enabled")
    # ### end Alembic commands ###
