"""shift_required_users_number

Revision ID: 15e924167158
Revises: 3ec95baef9a7
Create Date: 2022-06-10 13:18:42.719172

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "15e924167158"
down_revision = "3ec95baef9a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shifts", sa.Column("required_users_number", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shifts", "required_users_number")
    # ### end Alembic commands ###
