"""default_gcntags

Revision ID: 16c6e68ae49b
Revises: 13b080112d9c
Create Date: 2023-06-08 11:00:44.722186

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "16c6e68ae49b"
down_revision = "13b080112d9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_gcntags",
        sa.Column("requester_id", sa.Integer(), nullable=True),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("default_tag_name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("default_tag_name"),
    )
    op.create_index(
        op.f("ix_default_gcntags_created_at"),
        "default_gcntags",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_default_gcntags_requester_id"),
        "default_gcntags",
        ["requester_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_default_gcntags_requester_id"), table_name="default_gcntags")
    op.drop_index(op.f("ix_default_gcntags_created_at"), table_name="default_gcntags")
    op.drop_table("default_gcntags")
    # ### end Alembic commands ###
