"""Add free-text columns for spectra reducers and observers

Revision ID: 171e9ea18885
Revises: 1f4da189227e
Create Date: 2021-07-20 18:12:14.845079

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "171e9ea18885"
down_revision = "4ef77725b330"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spectrum_observers", sa.Column("external_observer", sa.String(), nullable=True)
    )
    op.add_column(
        "spectrum_reducers", sa.Column("external_reducer", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spectrum_reducers", "external_reducer")
    op.drop_column("spectrum_observers", "external_observer")
    # ### end Alembic commands ###
