"""New scanning report page

Revision ID: 17a1710698b9
Revises: 1593df0c0979
Create Date: 2025-02-27 17:47:33.853275

"""

import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "17a1710698b9"
down_revision = "1593df0c0979"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scanreports",
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_options", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scanreports_created_at"), "scanreports", ["created_at"], unique=False
    )
    op.create_table(
        "group_scan_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("scanreport_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["scanreport_id"], ["scanreports.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "group_scan_reports_forward_ind",
        "group_scan_reports",
        ["group_id", "scanreport_id"],
        unique=True,
    )
    op.create_index(
        "group_scan_reports_reverse_ind",
        "group_scan_reports",
        ["scanreport_id", "group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_scan_reports_created_at"),
        "group_scan_reports",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "scanreportitems",
        sa.Column("obj_id", sa.String(), nullable=False),
        sa.Column("scan_report_id", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["obj_id"], ["objs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["scan_report_id"], ["scanreports.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scanreportitems_created_at"),
        "scanreportitems",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scanreportitems_scan_report_id"),
        "scanreportitems",
        ["scan_report_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_scanreportitems_scan_report_id"), table_name="scanreportitems"
    )
    op.drop_index(op.f("ix_scanreportitems_created_at"), table_name="scanreportitems")
    op.drop_table("scanreportitems")
    op.drop_index(
        op.f("ix_group_scan_reports_created_at"), table_name="group_scan_reports"
    )
    op.drop_index("group_scan_reports_reverse_ind", table_name="group_scan_reports")
    op.drop_index("group_scan_reports_forward_ind", table_name="group_scan_reports")
    op.drop_table("group_scan_reports")
    op.drop_index(op.f("ix_scanreports_created_at"), table_name="scanreports")
    op.drop_table("scanreports")
    # ### end Alembic commands ###
