"""Test migration

Revision ID: 17fc6557b7ad
Revises: 675d41c71a2b
Create Date: 2022-08-27 21:15:10.039242

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "17fc6557b7ad"
down_revision = "675d41c71a2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
alter type "public"."followup_apis" rename to "followup_apis__old_version_to_be_dropped";

create type "public"."followup_apis" as enum ('ATLASAPI', 'KAITAPI', 'SEDMAPI', 'SEDMV2API', 'IOOAPI', 'IOIAPI', 'SPRATAPI', 'SINISTROAPI', 'SPECTRALAPI', 'FLOYDSAPI', 'MUSCATAPI', 'MMAAPI', 'PS1API', 'SLACKAPI', 'UVOTXRTAPI', 'UVOTXRTMMAAPI', 'ZTFAPI', 'ZTFMMAAPI');

alter table "public"."instruments" alter column api_classname type "public"."followup_apis" using api_classname::text::"public"."followup_apis";

alter table "public"."instruments" alter column api_classname_obsplan type "public"."followup_apis" using api_classname_obsplan::text::"public"."followup_apis";

drop type "public"."followup_apis__old_version_to_be_dropped";
    """
    )

    op.alter_column(
        "executedobservations",
        "observation_id",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
    )
    op.add_column(
        "executedobservations", sa.Column("target_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "executedobservations",
        "observation_id",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
    )
    op.drop_column("executedobservations", "target_name")
    # ### end Alembic commands ###
