"""galaxy migration

Revision ID: 19b187b11248
Revises: 171e9ea18885
Create Date: 2021-08-24 10:05:32.606237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b187b11248'
down_revision = '171e9ea18885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'galaxys',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('ra', sa.Float(), nullable=True),
        sa.Column('dec', sa.Float(), nullable=True),
        sa.Column('catalog_name', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('distmpc', sa.Float(), nullable=True),
        sa.Column('sfr_fuv', sa.Float(), nullable=True),
        sa.Column('mstar', sa.Float(), nullable=True),
        sa.Column('magb', sa.Float(), nullable=True),
        sa.Column('a', sa.Float(), nullable=True),
        sa.Column('b2a', sa.Float(), nullable=True),
        sa.Column('pa', sa.Float(), nullable=True),
        sa.Column('btc', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_galaxys_created_at'), 'galaxys', ['created_at'], unique=False
    )
    op.create_index(op.f('ix_galaxys_nested'), 'galaxys', ['nested'], unique=False)
    op.create_index('ix_galaxys_point', 'galaxys', ['x', 'y', 'z'], unique=False)
    op.add_column('objs', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('objs', sa.Column('y', sa.Float(), nullable=True))
    op.add_column('objs', sa.Column('z', sa.Float(), nullable=True))
    op.add_column('objs', sa.Column('nested', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_objs_nested'), 'objs', ['nested'], unique=False)
    op.create_index('ix_objs_point', 'objs', ['x', 'y', 'z'], unique=False)
    op.add_column('photometry', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('photometry', sa.Column('y', sa.Float(), nullable=True))
    op.add_column('photometry', sa.Column('z', sa.Float(), nullable=True))
    op.add_column('photometry', sa.Column('nested', sa.BigInteger(), nullable=True))
    op.create_index(
        op.f('ix_photometry_nested'), 'photometry', ['nested'], unique=False
    )
    op.create_index('ix_photometry_point', 'photometry', ['x', 'y', 'z'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photometry_point', table_name='photometry')
    op.drop_index(op.f('ix_photometry_nested'), table_name='photometry')
    op.drop_column('photometry', 'nested')
    op.drop_column('photometry', 'z')
    op.drop_column('photometry', 'y')
    op.drop_column('photometry', 'x')
    op.drop_index('ix_objs_point', table_name='objs')
    op.drop_index(op.f('ix_objs_nested'), table_name='objs')
    op.drop_column('objs', 'nested')
    op.drop_column('objs', 'z')
    op.drop_column('objs', 'y')
    op.drop_column('objs', 'x')
    op.drop_index('ix_galaxys_point', table_name='galaxys')
    op.drop_index(op.f('ix_galaxys_nested'), table_name='galaxys')
    op.drop_index(op.f('ix_galaxys_created_at'), table_name='galaxys')
    op.drop_table('galaxys')
    # ### end Alembic commands ###
