"""Add thumbnail is_grayscale

Revision ID: 19b72aac66cd
Revises: 3e1852612f34
Create Date: 2021-03-26 13:28:18.514981

"""
import requests

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

from skyportal.models import Thumbnail
from skyportal.utils.thumbnail import image_is_grayscale


# revision identifiers, used by Alembic.
revision = '19b72aac66cd'
down_revision = '3e1852612f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'thumbnails',
        sa.Column('is_grayscale', sa.Boolean(), nullable=False, default=False),
    )

    # Attach a sqlalchemy Session to the env connection
    session = Session(bind=op.get_bind())
    thumbnails = session.query(Thumbnail).all()
    for thumbnail in thumbnails:
        if thumbnail.file_uri is not None:
            thumbnail.is_grayscale = image_is_grayscale(thumbnail.file_uri)
        else:
            try:
                thumbnail.is_grayscale = image_is_grayscale(
                    requests.get(thumbnail.public_url, stream=True).raw
                )
            except requests.exceptions.RequestException:
                pass

    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thumbnails', 'is_grayscale')
    # ### end Alembic commands ###
