"""Add thumbnail is_grayscale

Revision ID: 19b72aac66cd
Revises: 3e1852612f34
Create Date: 2021-03-26 13:28:18.514981

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "19b72aac66cd"
down_revision = "1562ff135257"
branch_labels = None
depends_on = None


def upgrade():
    # Add the column with a server_default so that there are no NULL values when the
    # column is created initially
    op.add_column(
        "thumbnails",
        sa.Column("is_grayscale", sa.Boolean(), nullable=False, server_default="False"),
    )
    # But we actually want to drop the server default since we're using the SQLAlchemy
    # default within models.py
    op.alter_column("thumbnails", "is_grayscale", server_default=None)

    # It would take too long to run the image_is_grayscale on the entire database for
    # production-scale instances within the migration, so we just leave all old
    # thumbnails as colored by default. Use an external script to retroactively fix
    # the old thumbnails if needed.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("thumbnails", "is_grayscale")
    # ### end Alembic commands ###
