"""galaxy table

Revision ID: 1aeb080b0eda
Revises: 80434b53562c
Create Date: 2021-11-20 14:58:47.726104

"""

import healpix_alchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1aeb080b0eda"
down_revision = "80434b53562c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "galaxys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("ra", sa.Float(), nullable=True),
        sa.Column("dec", sa.Float(), nullable=True),
        sa.Column("catalog_name", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("alt_name", sa.String(), nullable=True),
        sa.Column("distmpc", sa.Float(), nullable=True),
        sa.Column("distmpc_unc", sa.Float(), nullable=True),
        sa.Column("healpix", healpix_alchemy.types.Point(), nullable=True),
        sa.Column("redshift", sa.Float(), nullable=True),
        sa.Column("redshift_error", sa.Float(), nullable=True),
        sa.Column("sfr_fuv", sa.Float(), nullable=True),
        sa.Column("mstar", sa.Float(), nullable=True),
        sa.Column("magb", sa.Float(), nullable=True),
        sa.Column("a", sa.Float(), nullable=True),
        sa.Column("b2a", sa.Float(), nullable=True),
        sa.Column("pa", sa.Float(), nullable=True),
        sa.Column("btc", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_galaxys_created_at"), "galaxys", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_galaxys_healpix"), "galaxys", ["healpix"], unique=False)
    op.execute(
        """ CREATE INDEX ix_galaxys_point ON public.galaxys USING btree (((cosd(ra) * cosd("dec"))), ((sind(ra) * cosd("dec"))), sind("dec"));
               """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_galaxys_healpix"), table_name="galaxys")
    op.drop_index(op.f("ix_galaxys_created_at"), table_name="galaxys")
    op.drop_index(op.f("ix_galaxys_point"), table_name="galaxys")
    op.drop_table("galaxys")
    # ### end Alembic commands ###
