"""Foreign key updates for proper deletion cascades

Revision ID: 1c2d593e9778
Revises: 99958ac9a5b1
Create Date: 2021-01-29 14:33:23.468114

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1c2d593e9778"
down_revision = "99958ac9a5b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "facilitytransactions",
        "followup_request_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "facilitytransactions",
        "initiator_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_constraint(
        "facilitytransactions_followup_request_id_fkey",
        "facilitytransactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "facilitytransactions",
        "followuprequests",
        ["followup_request_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "followuprequests",
        "last_modified_by_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "followuprequests", "requester_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        "followuprequests_requester_id_fkey", "followuprequests", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "followuprequests", "users", ["requester_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(
        "photometry_instrument_id_fkey", "photometry", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "photometry", "instruments", ["instrument_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "spectra_followup_request_id_fkey", "spectra", type_="foreignkey"
    )
    op.drop_constraint("spectra_assignment_id_fkey", "spectra", type_="foreignkey")
    op.create_foreign_key(
        None,
        "spectra",
        "classicalassignments",
        ["assignment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "spectra",
        "followuprequests",
        ["followup_request_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "spectra", type_="foreignkey")
    op.drop_constraint(None, "spectra", type_="foreignkey")
    op.create_foreign_key(
        "spectra_assignment_id_fkey",
        "spectra",
        "classicalassignments",
        ["assignment_id"],
        ["id"],
    )
    op.create_foreign_key(
        "spectra_followup_request_id_fkey",
        "spectra",
        "followuprequests",
        ["followup_request_id"],
        ["id"],
    )
    op.drop_constraint(None, "photometry", type_="foreignkey")
    op.create_foreign_key(
        "photometry_instrument_id_fkey",
        "photometry",
        "instruments",
        ["instrument_id"],
        ["id"],
    )
    op.drop_constraint(None, "followuprequests", type_="foreignkey")
    op.create_foreign_key(
        "followuprequests_requester_id_fkey",
        "followuprequests",
        "users",
        ["requester_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "followuprequests", "requester_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "followuprequests",
        "last_modified_by_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(None, "facilitytransactions", type_="foreignkey")
    op.create_foreign_key(
        "facilitytransactions_followup_request_id_fkey",
        "facilitytransactions",
        "followuprequests",
        ["followup_request_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "facilitytransactions",
        "initiator_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "facilitytransactions",
        "followup_request_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
