"""Test migration

Revision ID: 286d8e9f8c76
Revises: 1c2d593e9778
Create Date: 2021-02-16 19:02:08.547952

"""

# revision identifiers, used by Alembic.
revision = '286d8e9f8c76'
down_revision = '1c2d593e9778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
