"""observation plans submission

Revision ID: 29fbb7ea2c4f
Revises: d6b24747693a
Create Date: 2022-02-19 16:30:40.382089

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "29fbb7ea2c4f"
down_revision = "d6b24747693a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "facilitytransactions",
        sa.Column("observation_plan_request_id", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_facilitytransactions_observation_plan_request_id"),
        "facilitytransactions",
        ["observation_plan_request_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "facilitytransactions",
        "observationplanrequests",
        ["observation_plan_request_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("instrumentfields", sa.Column("ra", sa.Float(), nullable=True))
    op.add_column("instrumentfields", sa.Column("dec", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instrumentfields", "dec")
    op.drop_column("instrumentfields", "ra")
    op.drop_constraint(None, "facilitytransactions", type_="foreignkey")
    op.drop_index(
        op.f("ix_facilitytransactions_observation_plan_request_id"),
        table_name="facilitytransactions",
    )
    op.drop_column("facilitytransactions", "observation_plan_request_id")
    # ### end Alembic commands ###
