"""listing_params

Revision ID: 2a5480c47f09
Revises: 5afbab3b73c4
Create Date: 2023-05-17 08:45:38.681059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a5480c47f09'
down_revision = '5afbab3b73c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'listings',
        sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'params')
    # ### end Alembic commands ###
