"""Create Rubin ObsLocTAP API for observation retrieval

Revision ID: 2c4c3061af22
Revises: 52b02a40ac4d
Create Date: 2026-07-23 16:05:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "2c4c3061af22"
down_revision = "52b02a40ac4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'RUBINMMAAPI'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
