"""MMADetector migration

Revision ID: 2c856b2845f2
Revises: 675d41c71a2b
Create Date: 2022-08-31 02:36:52.515380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c856b2845f2'
down_revision = '675d41c71a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'mmadetectors',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('nickname', sa.String(), nullable=False),
        sa.Column(
            'type',
            sa.Enum(
                'gravitational-wave',
                'neutrino',
                'gamma-ray-burst',
                name='mma_detector_types',
            ),
            nullable=False,
        ),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lon', sa.Float(), nullable=True),
        sa.Column('elevation', sa.Float(), nullable=True),
        sa.Column(
            'fixed_location', sa.Boolean(), server_default='true', nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_index(
        op.f('ix_mmadetectors_created_at'), 'mmadetectors', ['created_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mmadetectors_created_at'), table_name='mmadetectors')
    op.drop_table('mmadetectors')
    # ### end Alembic commands ###
