"""user_affiliations

Revision ID: 336795744e40
Revises: 5b756b18ff2d
Create Date: 2022-07-07 21:05:14.543407

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "336795744e40"
down_revision = "5b756b18ff2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "affiliations", sa.ARRAY(sa.String()), server_default="{}", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "affiliations")
    # ### end Alembic commands ###
