"""ps1 migration

Revision ID: 33ef976ca10f
Revises: 5f8328a76607
Create Date: 2022-02-19 14:50:54.172754

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "33ef976ca10f"
down_revision = "5f8328a76607"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add PS1API in the right place
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'PS1API' AFTER 'MMAAPI'"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
