"""ps1 migration

Revision ID: 33ef976ca10f
Revises: d6b24747693a
Create Date: 2022-02-19 14:50:54.172754

"""
# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ef976ca10f'
down_revision = 'd6b24747693a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
