"""Host index migration

Revision ID: 38f9789d2dff
Revises: f027c37fabed
Create Date: 2023-05-23 23:10:07.123701

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "38f9789d2dff"
down_revision = "f027c37fabed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_objs_host_id"), "objs", ["host_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_objs_host_id"), table_name="objs")
    # ### end Alembic commands ###
