"""brokers

Revision ID: 3b123ce8702b
Revises: d7b2f4a1c9e0
Create Date: 2026-07-03 16:45:42.951457

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "3b123ce8702b"
down_revision = "a1c0ss1d0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brokers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "broker_classname",
            sa.Enum(
                "GENERICBROKER",
                "LASAIRBROKER",
                "BABAMULBROKER",
                "BOOMBROKER",
                "FINKBROKER",
                "ALERCEBROKER",
                "ANTARESBROKER",
                "PITTGOOGLEBROKER",
                "AMPELBROKER",
                name="broker_apis",
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "_altdata",
            sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_brokers_created_at"), "brokers", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_brokers_created_at"), table_name="brokers")
    op.drop_table("brokers")
    op.execute('DROP TYPE "public"."broker_apis"')
    # ### end Alembic commands ###
