"""healpix_alchemy migration

Revision ID: 4047c470ab83
Revises: 5b4d9d54142e
Create Date: 2021-08-24 13:35:39.484659

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '4047c470ab83'
down_revision = '5b4d9d54142e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objs', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('objs', sa.Column('y', sa.Float(), nullable=True))
    op.add_column('objs', sa.Column('z', sa.Float(), nullable=True))

    conn = op.get_bind()
    # Back-populate existing objs rows
    conn.execute(
        sa.sql.text(
            """
            UPDATE objs SET
            x = cos(radians(ra)) * cos(radians(dec)),
            y = sin(radians(ra)) * cos(radians(dec)),
            z = sin(radians(dec));

            """
        )
    )

    op.add_column('objs', sa.Column('nested', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_objs_nested'), 'objs', ['nested'], unique=False)
    op.add_column('photometry', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('photometry', sa.Column('y', sa.Float(), nullable=True))
    op.add_column('photometry', sa.Column('z', sa.Float(), nullable=True))

    # Back-populate existing photometry rows
    conn.execute(
        sa.sql.text(
            """
            UPDATE photometry SET
            x = cos(radians(ra)) * cos(radians(dec)),
            y = sin(radians(ra)) * cos(radians(dec)),
            z = sin(radians(dec));

            """
        )
    )

    op.add_column('photometry', sa.Column('nested', sa.BigInteger(), nullable=True))
    op.create_index(
        op.f('ix_photometry_nested'), 'photometry', ['nested'], unique=False
    )

    # Drop existing old index
    op.drop_index('ix_photometry_point', table_name='photometry')
    op.drop_index('ix_objs_point', table_name='objs')

    # Create new index
    op.create_index('ix_objs_point', 'objs', ['x', 'y', 'z'], unique=False)
    op.create_index('ix_photometry_point', 'photometry', ['x', 'y', 'z'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photometry_point', table_name='photometry')
    op.drop_index('ix_objs_point', table_name='objs')
    op.drop_index(op.f('ix_photometry_nested'), table_name='photometry')
    op.drop_column('photometry', 'nested')
    op.drop_column('photometry', 'z')
    op.drop_column('photometry', 'y')
    op.drop_column('photometry', 'x')
    op.drop_index(op.f('ix_objs_nested'), table_name='objs')
    op.drop_column('objs', 'nested')
    op.drop_column('objs', 'z')
    op.drop_column('objs', 'y')
    op.drop_column('objs', 'x')
    # ### end Alembic commands ###
