"""Allocation default

Revision ID: 415cd17ac788
Revises: 8acd303bd097
Create Date: 2022-05-22 18:43:06.301870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415cd17ac788'
down_revision = '8acd303bd097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'allocations',
        sa.Column(
            'default_share_group_ids',
            sa.ARRAY(sa.Integer()),
            nullable=True,
            comment='List of default group IDs to share date with',
        ),
    )

    op.alter_column(
        'allocations',
        'default_share_group_ids',
        existing_type=sa.ARRAY(sa.INTEGER()),
        comment='List of default group IDs to share data with',
        existing_comment='List of default group IDs to share date with',
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allocations', 'default_share_group_ids')
    # ### end Alembic commands ###
