"""Default survey efficiencies migration

Revision ID: 43306550c9d0
Revises: 765363c68b5b
Create Date: 2022-11-03 01:09:36.821167

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "43306550c9d0"
down_revision = "765363c68b5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "defaultsurveyefficiencyrequests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("default_observationplan_request_id", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_observationplan_request_id"],
            ["defaultobservationplanrequests.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_defaultsurveyefficiencyrequests_created_at"),
        "defaultsurveyefficiencyrequests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_defaultsurveyefficiencyrequests_default_observationplan_request_id"),
        "defaultsurveyefficiencyrequests",
        ["default_observationplan_request_id"],
        unique=False,
    )
    op.add_column(
        "defaultobservationplanrequests",
        sa.Column("default_plan_name", sa.String(), nullable=False),
    )
    op.create_unique_constraint(
        None, "defaultobservationplanrequests", ["default_plan_name"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "defaultobservationplanrequests", type_="unique")
    op.drop_column("defaultobservationplanrequests", "default_plan_name")
    op.drop_index(
        op.f("ix_defaultsurveyefficiencyrequests_default_observationplan_request_id"),
        table_name="defaultsurveyefficiencyrequests",
    )
    op.drop_index(
        op.f("ix_defaultsurveyefficiencyrequests_created_at"),
        table_name="defaultsurveyefficiencyrequests",
    )
    op.drop_table("defaultsurveyefficiencyrequests")
    # ### end Alembic commands ###
