"""TRT migration

Revision ID: 468435875f30
Revises: 430a8a5f3c18
Create Date: 2024-03-29 15:48:56.979223

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = '468435875f30'
down_revision = '430a8a5f3c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
alter type "public"."followup_apis" rename to "followup_apis__old_version_to_be_dropped";

create type "public"."followup_apis" as enum ('MMAAPI', 'GENERICAPI', 'SLACKAPI', 'ATLASAPI', 'GROWTHINDIAMMAAPI', 'KAITAPI', 'SEDMAPI', 'SEDMV2API', 'IOOAPI', 'IOIAPI', 'SPRATAPI', 'SINISTROAPI', 'SPECTRALAPI', 'FLOYDSAPI', 'MUSCATAPI', 'NICERAPI', 'PS1API', 'UVOTXRTAPI', 'UVOTXRTMMAAPI', 'TESSAPI', 'TRTAPI', 'WINTERAPI', 'ZTFAPI', 'ZTFMMAAPI');

alter table "public"."instruments" alter column api_classname type "public"."followup_apis" using api_classname::text::"public"."followup_apis";

alter table "public"."instruments" alter column api_classname_obsplan type "public"."followup_apis" using api_classname_obsplan::text::"public"."followup_apis";

drop type "public"."followup_apis__old_version_to_be_dropped";
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
