"""Test migration

Revision ID: 46c79f9b64e5
Revises: 85e5b0be85a2
Create Date: 2022-11-16 17:33:59.429351

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "46c79f9b64e5"
down_revision = "85e5b0be85a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sourcesconfirmedingcns", sa.Column("explanation", sa.String(), nullable=True)
    )
    op.drop_column("sourcesconfirmedingcns", "explaination")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sourcesconfirmedingcns",
        sa.Column("explaination", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("sourcesconfirmedingcns", "explanation")
    # ### end Alembic commands ###
