"""instrument field sequence

Revision ID: 486c860564a2
Revises: dc7f29329a89
Create Date: 2022-03-10 18:29:48.866401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486c860564a2'
down_revision = 'dc7f29329a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'instrumentfields',
        'field_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.add_column('instruments', sa.Column('region', sa.String(), nullable=True))
    op.execute('create sequence "public"."seq_field_id";')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'region')
    op.alter_column(
        'instrumentfields',
        'field_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
