"""added alias column on obj

Revision ID: 5374c88c91dd
Revises: 31d3251df20b
Create Date: 2021-05-12 18:04:19.824529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5374c88c91dd'
down_revision = '31d3251df20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objs', sa.Column('alias', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objs', 'alias')
    # ### end Alembic commands ###
