"""catalog query migration

Revision ID: 5466bd5ce2e5
Revises: 2510cf8ad164
Create Date: 2022-09-10 22:42:16.319996

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5466bd5ce2e5"
down_revision = "2510cf8ad164"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_queries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("allocation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allocation_id"], ["allocations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_queries_allocation_id"),
        "catalog_queries",
        ["allocation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_queries_created_at"),
        "catalog_queries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_queries_requester_id"),
        "catalog_queries",
        ["requester_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_queries_status"), "catalog_queries", ["status"], unique=False
    )
    op.create_table(
        "catalog_queries_groups",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_querie_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_querie_id"], ["catalog_queries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "catalog_queries_groups_forward_ind",
        "catalog_queries_groups",
        ["catalog_querie_id", "group_id"],
        unique=True,
    )
    op.create_index(
        "catalog_queries_groups_reverse_ind",
        "catalog_queries_groups",
        ["group_id", "catalog_querie_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_queries_groups_created_at"),
        "catalog_queries_groups",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_catalog_queries_groups_created_at"),
        table_name="catalog_queries_groups",
    )
    op.drop_index(
        "catalog_queries_groups_reverse_ind", table_name="catalog_queries_groups"
    )
    op.drop_index(
        "catalog_queries_groups_forward_ind", table_name="catalog_queries_groups"
    )
    op.drop_table("catalog_queries_groups")
    op.drop_index(op.f("ix_catalog_queries_status"), table_name="catalog_queries")
    op.drop_index(op.f("ix_catalog_queries_requester_id"), table_name="catalog_queries")
    op.drop_index(op.f("ix_catalog_queries_created_at"), table_name="catalog_queries")
    op.drop_index(
        op.f("ix_catalog_queries_allocation_id"), table_name="catalog_queries"
    )
    op.drop_table("catalog_queries")
    # ### end Alembic commands ###
