"""observingruns_end

Revision ID: 5516eb897b1c
Revises: bc7afebe918f
Create Date: 2023-10-08 10:10:00.585039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5516eb897b1c'
down_revision = 'bc7afebe918f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'observingruns', sa.Column('_calendar_noon', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'observingruns', sa.Column('run_end_utc', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observingruns', 'run_end_utc')
    op.drop_column('observingruns', '_calendar_noon')
    # ### end Alembic commands ###
