"""Galaxy index

Revision ID: 556169569def
Revises: 2ea665ed5e0d
Create Date: 2022-07-18 14:38:12.403052

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "556169569def"
down_revision = "2ea665ed5e0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_galaxys_distmpc"), "galaxys", ["distmpc"], unique=False)
    op.create_index(op.f("ix_galaxys_redshift"), "galaxys", ["redshift"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_galaxys_redshift"), table_name="galaxys")
    op.drop_index(op.f("ix_galaxys_distmpc"), table_name="galaxys")
    # ### end Alembic commands ###
