"""Automatically publish source when created

Revision ID: 581111398381
Revises: b0f0b2a30357
Create Date: 2024-08-10 15:06:00.098983

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581111398381'
down_revision = 'b0f0b2a30357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'publicreleases',
        sa.Column('automatically_publish', sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicreleases', 'automatically_publish')
    # ### end Alembic commands ###
