"""photometry magref

Revision ID: 581774928d27
Revises: 1a43ee08a734
Create Date: 2022-03-30 15:14:59.284519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581774928d27'
down_revision = '1a43ee08a734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photometry', sa.Column('magref', sa.Float(), nullable=True))
    op.add_column('photometry', sa.Column('magref_unc', sa.Float(), nullable=True))
    op.create_index(
        op.f('ix_photometry_magref'), 'photometry', ['magref'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photometry_magref'), table_name='photometry')
    op.drop_column('photometry', 'magref_unc')
    op.drop_column('photometry', 'magref')
    # ### end Alembic commands ###
