"""atlasapi enum

Revision ID: 59ba401a110a
Revises: 46a40b35cdbb
Create Date: 2022-01-27 13:24:35.958075

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '59ba401a110a'
down_revision = '46a40b35cdbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
alter type "public"."followup_apis" rename to "followup_apis__old_version_to_be_dropped";

create type "public"."followup_apis" as enum ('ATLASAPI', 'KAITAPI', 'SEDMAPI', 'SEDMV2API', 'IOOAPI', 'IOIAPI', 'SPRATAPI', 'SINISTROAPI', 'SPECTRALAPI', 'FLOYDSAPI', 'MUSCATAPI', 'SLACKAPI', 'ZTFAPI');

alter table "public"."instruments" alter column api_classname type "public"."followup_apis" using api_classname::text::"public"."followup_apis";

drop type "public"."followup_apis__old_version_to_be_dropped" cascade;
"""
    )
    # ### end Alembic commands ###

    op.add_column(
        'instruments',
        sa.Column(
            'api_classname_obsplan',
            sa.Enum(
                'ATLASAPI',
                'KAITAPI',
                'SEDMAPI',
                'SEDMV2API',
                'IOOAPI',
                'IOIAPI',
                'SPRATAPI',
                'SINISTROAPI',
                'SPECTRALAPI',
                'FLOYDSAPI',
                'MUSCATAPI',
                'SLACKAPI',
                'ZTFAPI',
                name='followup_apis',
            ),
            nullable=True,
        ),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'api_classname_obsplan')
    # ### end Alembic commands ###
