"""NED migration

Revision ID: 5afbab3b73c4
Revises: 59c6db1df47f
Create Date: 2023-05-15 21:55:30.180748

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5afbab3b73c4"
down_revision = "59c6db1df47f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("galaxys", sa.Column("sfr_w4", sa.Float(), nullable=True))
    op.add_column("galaxys", sa.Column("mag_fuv", sa.Float(), nullable=True))
    op.add_column("galaxys", sa.Column("mag_nuv", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("galaxys", "mag_nuv")
    op.drop_column("galaxys", "mag_fuv")
    op.drop_column("galaxys", "sfr_w4")
    # ### end Alembic commands ###
