"""add spectrum type enum

Revision ID: 5b4d9d54142e
Revises: 171e9ea18885
Create Date: 2021-10-01 11:36:07.537608

"""

import sqlalchemy as sa

from alembic import op
from skyportal.enum_types import ALLOWED_SPECTRUM_TYPES, default_spectrum_type

# revision identifiers, used by Alembic.
revision = "5b4d9d54142e"
down_revision = "171e9ea18885"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""
        DO $$ BEGIN
          CREATE TYPE "spectrumtypes" AS ENUM ({", ".join(f"'{t}'" for t in ALLOWED_SPECTRUM_TYPES)} );
        EXCEPTION
          WHEN duplicate_object THEN null;
        END $$;
        """
    )
    op.add_column(
        "spectra",
        sa.Column(
            "type",
            sa.Enum(*ALLOWED_SPECTRUM_TYPES, name="spectrumtypes"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###

    spectra = sa.Table("spectra", sa.MetaData(), sa.Column("type", sa.Enum()))
    conn = op.get_bind()
    conn.execute(
        spectra.update()
        .where(spectra.c.type.is_(None))
        .values(type=default_spectrum_type)
    )
    op.alter_column("spectra", "type", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spectra", "type")
    # ### end Alembic commands ###
