"""Add UserNotification table

Revision ID: 5f2ba5579a79
Revises: b74a9ff3b29d
Create Date: 2021-01-20 16:50:18.149775

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5f2ba5579a79"
down_revision = "b74a9ff3b29d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usernotifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usernotifications_read"), "usernotifications", ["read"], unique=False
    )
    op.create_index(
        op.f("ix_usernotifications_user_id"),
        "usernotifications",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usernotifications_user_id"), table_name="usernotifications")
    op.drop_index(op.f("ix_usernotifications_read"), table_name="usernotifications")
    op.drop_table("usernotifications")
    # ### end Alembic commands ###
