"""instrument contour summary

Revision ID: 5f8328a76607
Revises: 6a769fd6d909
Create Date: 2022-02-22 15:44:13.011868

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5f8328a76607"
down_revision = "6a769fd6d909"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instrumentfields",
        sa.Column(
            "contour_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instrumentfields", "contour_summary")
    # ### end Alembic commands ###
