"""add GCN comments

Revision ID: 66ed6017e9ac
Revises: f9611048498a
Create Date: 2022-01-21 18:24:30.804782

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "66ed6017e9ac"
down_revision = "9167685a2710"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments_on_gcns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("attachment_name", sa.String(), nullable=True),
        sa.Column("attachment_bytes", sa.LargeBinary(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("bot", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("gcn_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["gcn_id"], ["gcnevents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comments_on_gcns_author_id"),
        "comments_on_gcns",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comments_on_gcns_created_at"),
        "comments_on_gcns",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comments_on_gcns_gcn_id"), "comments_on_gcns", ["gcn_id"], unique=False
    )
    op.create_table(
        "group_comments_on_gcns",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("comments_on_gcn_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comments_on_gcn_id"], ["comments_on_gcns.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "group_comments_on_gcns_forward_ind",
        "group_comments_on_gcns",
        ["group_id", "comments_on_gcn_id"],
        unique=True,
    )
    op.create_index(
        "group_comments_on_gcns_reverse_ind",
        "group_comments_on_gcns",
        ["comments_on_gcn_id", "group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_comments_on_gcns_created_at"),
        "group_comments_on_gcns",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_group_comments_on_gcns_created_at"),
        table_name="group_comments_on_gcns",
    )
    op.drop_index(
        "group_comments_on_gcns_reverse_ind", table_name="group_comments_on_gcns"
    )
    op.drop_index(
        "group_comments_on_gcns_forward_ind", table_name="group_comments_on_gcns"
    )
    op.drop_table("group_comments_on_gcns")
    op.drop_index(op.f("ix_comments_on_gcns_gcn_id"), table_name="comments_on_gcns")
    op.drop_index(op.f("ix_comments_on_gcns_created_at"), table_name="comments_on_gcns")
    op.drop_index(op.f("ix_comments_on_gcns_author_id"), table_name="comments_on_gcns")
    op.drop_table("comments_on_gcns")
    # ### end Alembic commands ###
