"""make classification prob non-nullable, set default to 1

Revision ID: 67109d315f17
Revises: 065726baac98
Create Date: 2022-10-21 19:25:22.336778

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67109d315f17'
down_revision = '065726baac98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'classifications',
        'probability',
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
        server_default=1.0,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'classifications',
        'probability',
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###
