"""tablelock migration

Revision ID: 6928ae655672
Revises: 2b8addba3e86
Create Date: 2026-05-18 18:45:51.882812

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "6928ae655672"
down_revision = "2b8addba3e86"
branch_labels = None
depends_on = None


def upgrade():
    # Defensive dedupe so the unique index below can never fail to apply.
    # On Fritz prod this is a no-op (verified zero duplicates pre-migration);
    # downstream deployments may have history we don't see. Keeps the row
    # with the most recent last_full_update (NULLS last), id as tie-breaker.
    op.execute(
        """
        DELETE FROM photstats
        WHERE id NOT IN (
            SELECT DISTINCT ON (obj_id) id
            FROM photstats
            ORDER BY obj_id, last_full_update DESC NULLS LAST, id DESC
        )
        """
    )
    op.drop_index(op.f("ix_photstats_obj_id"), table_name="photstats")
    op.create_index(op.f("ix_photstats_obj_id"), "photstats", ["obj_id"], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photstats_obj_id"), table_name="photstats")
    op.create_index(op.f("ix_photstats_obj_id"), "photstats", ["obj_id"], unique=False)
    # ### end Alembic commands ###
