"""tablelock migration

Revision ID: 6928ae655672
Revises: 2b8addba3e86
Create Date: 2026-05-18 18:45:51.882812

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "6928ae655672"
down_revision = "2b8addba3e86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photstats_obj_id"), table_name="photstats")
    op.create_index(op.f("ix_photstats_obj_id"), "photstats", ["obj_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photstats_obj_id"), table_name="photstats")
    op.create_index(op.f("ix_photstats_obj_id"), "photstats", ["obj_id"], unique=False)
    # ### end Alembic commands ###
