"""add description column to group table

Revision ID: 695affb5e503
Revises: 529166dc7732
Create Date: 2022-02-17 09:17:02.659131

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "695affb5e503"
down_revision = "529166dc7732"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "description")
    # ### end Alembic commands ###
