"""sncosmo bump

Revision ID: 6a769fd6d909
Revises: 29fbb7ea2c4f
Create Date: 2022-02-23 22:16:08.873220

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "6a769fd6d909"
down_revision = "29fbb7ea2c4f"
branch_labels = None
depends_on = None


def upgrade():
    # add filters from sncosmo 2.7.0 in the right place
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'f062' AFTER '4shooter2::i'"
        )
        op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'f087' AFTER 'f062'")
        op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'f106' AFTER 'f087'")
        op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'f129' AFTER 'f106'")
        op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'f158' AFTER 'f129'")
        op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'f184' AFTER 'f158'")
        op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'f213' AFTER 'f184'")
        op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'f146' AFTER 'f213'")

        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'ps1::open' AFTER 'uvot::white'"
        )
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'ps1::g' AFTER 'ps1::open'"
        )
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'ps1::r' AFTER 'ps1::g'"
        )
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'ps1::i' AFTER 'ps1::r'"
        )
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'ps1::z' AFTER 'ps1::i'"
        )
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'ps1::y' AFTER 'ps1::z'"
        )
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'ps1::w' AFTER 'ps1::y'"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
