"""GCN crossmatch migration

Revision ID: 6f23bbeb119d
Revises: f027c37fabed
Create Date: 2023-05-20 20:47:34.554780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f23bbeb119d'
down_revision = 'f027c37fabed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'objs', sa.Column('gcn_crossmatch', sa.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objs', 'gcn_crossmatch')
    # ### end Alembic commands ###
