"""create sensitivity data column

Revision ID: 73bc8919f190
Revises: 529166dc7732
Create Date: 2022-02-16 18:31:00.739464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73bc8919f190'
down_revision = '529166dc7732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'instruments',
        sa.Column(
            'sensitivity_data',
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'sensitivity_data')
    # ### end Alembic commands ###
