"""Add SPRING camera

Revision ID: 7678f8674917
Revises: 9f2a7c3e1b45
Create Date: 2026-01-24 20:30:27.205614

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "7678f8674917"
down_revision = "9f2a7c3e1b45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add SPRINGAPI in the right place
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'SPRINGAPI' AFTER 'WINTERAPI'"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
