"""Instrument configuration migration

Revision ID: 77788b2b56b2
Revises: 2a5480c47f09
Create Date: 2023-05-18 16:49:17.930836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77788b2b56b2'
down_revision = '2a5480c47f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'instruments',
        sa.Column(
            'configuration_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'configuration_data')
    # ### end Alembic commands ###
