"""adding new table for the source tag

Revision ID: 778b24fe579d
Revises: 9239216843f5
Create Date: 2025-05-06 14:11:20.188193

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "778b24fe579d"
down_revision = "9239216843f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("obj_tag_author_id_fkey", "obj_tag", type_="foreignkey")
    op.create_foreign_key(
        None, "obj_tag", "users", ["author_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "obj_tag", type_="foreignkey")
    op.create_foreign_key(
        "obj_tag_author_id_fkey",
        "obj_tag",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
