"""Followuprequests add comments

Revision ID: 77c4af61eea6
Revises: 0322f907b589
Create Date: 2024-03-20 23:25:49.628883

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "77c4af61eea6"
down_revision = "468435875f30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("followuprequests", sa.Column("comment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("followuprequests", "comment")
    # ### end Alembic commands ###
