"""Followuprequests add comments

Revision ID: 77c4af61eea6
Revises: 0322f907b589
Create Date: 2024-03-20 23:25:49.628883

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c4af61eea6'
down_revision = 'af970c6b6b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followuprequests', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followuprequests', 'comment')
    # ### end Alembic commands ###
