"""add spectrum label

Revision ID: 7a57648d870d
Revises: 5b4d9d54142e
Create Date: 2021-10-07 11:06:42.384654

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7a57648d870d"
down_revision = "5b4d9d54142e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spectra", sa.Column("label", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spectra", "label")
    # ### end Alembic commands ###
