"""notice_skymap_status

Revision ID: 7aa56a5355db
Revises: 0943fbb6faf0
Create Date: 2023-03-21 22:08:38.833636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa56a5355db'
down_revision = '0943fbb6faf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'gcnnotices',
        sa.Column(
            'has_localization', sa.Boolean(), nullable=False, server_default='true'
        ),
    )
    op.add_column(
        'gcnnotices',
        sa.Column(
            'localization_ingested',
            sa.Boolean(),
            nullable=False,
            server_default='false',
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gcnnotices', 'localization_ingested')
    op.drop_column('gcnnotices', 'has_localization')
    # ### end Alembic commands ###
