"""shift users

Revision ID: 7c814f8b0c31
Revises: 1a43ee08a734
Create Date: 2022-03-28 19:13:36.315024

"""




# revision identifiers, used by Alembic.
revision = '7c814f8b0c31'
down_revision = '1a43ee08a734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
