"""HST/Chandra migration

Revision ID: 7f0f99475b54
Revises: b854bf5d22b3
Create Date: 2024-06-10 09:46:29.229871

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = '7f0f99475b54'
down_revision = 'b854bf5d22b3'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
alter type "public"."thumbnail_types" rename to "thumbnail_types__old_version_to_be_dropped";

create type "public"."thumbnail_types" as enum ('new', 'ref', 'sub', 'sdss', 'dr8', 'ls', 'ps1', 'hst', 'chandra', 'new_gz', 'ref_gz', 'sub_gz');

alter table "public"."thumbnails" alter column type type "public"."thumbnail_types" using type::text::"public"."thumbnail_types";

drop type "public"."thumbnail_types__old_version_to_be_dropped";
"""
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
