"""spectrum_annotations

Revision ID: 80434b53562c
Revises: 5b4d9d54142e
Create Date: 2021-10-07 14:19:46.937769

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "80434b53562c"
down_revision = "7a57648d870d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotations_on_spectra",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("spectrum_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("obj_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["obj_id"], ["objs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spectrum_id"], ["spectra.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spectrum_id", "origin"),
    )
    op.create_index(
        op.f("ix_annotations_on_spectra_author_id"),
        "annotations_on_spectra",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotations_on_spectra_created_at"),
        "annotations_on_spectra",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotations_on_spectra_obj_id"),
        "annotations_on_spectra",
        ["obj_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotations_on_spectra_origin"),
        "annotations_on_spectra",
        ["origin"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotations_on_spectra_spectrum_id"),
        "annotations_on_spectra",
        ["spectrum_id"],
        unique=False,
    )
    op.create_table(
        "group_annotations_on_spectra",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("annotations_on_spectr_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotations_on_spectr_id"],
            ["annotations_on_spectra.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "group_annotations_on_spectra_forward_ind",
        "group_annotations_on_spectra",
        ["group_id", "annotations_on_spectr_id"],
        unique=True,
    )
    op.create_index(
        "group_annotations_on_spectra_reverse_ind",
        "group_annotations_on_spectra",
        ["annotations_on_spectr_id", "group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_annotations_on_spectra_created_at"),
        "group_annotations_on_spectra",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_group_annotations_on_spectra_created_at"),
        table_name="group_annotations_on_spectra",
    )
    op.drop_index(
        "group_annotations_on_spectra_reverse_ind",
        table_name="group_annotations_on_spectra",
    )
    op.drop_index(
        "group_annotations_on_spectra_forward_ind",
        table_name="group_annotations_on_spectra",
    )
    op.drop_table("group_annotations_on_spectra")
    op.drop_index(
        op.f("ix_annotations_on_spectra_spectrum_id"),
        table_name="annotations_on_spectra",
    )
    op.drop_index(
        op.f("ix_annotations_on_spectra_origin"), table_name="annotations_on_spectra"
    )
    op.drop_index(
        op.f("ix_annotations_on_spectra_obj_id"), table_name="annotations_on_spectra"
    )
    op.drop_index(
        op.f("ix_annotations_on_spectra_created_at"),
        table_name="annotations_on_spectra",
    )
    op.drop_index(
        op.f("ix_annotations_on_spectra_author_id"), table_name="annotations_on_spectra"
    )
    op.drop_table("annotations_on_spectra")
    # ### end Alembic commands ###
