"""gcn_aliases

Revision ID: 809e29e0c0c7
Revises: 675d41c71a2b
Create Date: 2022-07-28 15:58:41.631666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809e29e0c0c7'
down_revision = '675d41c71a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'gcnevents',
        sa.Column(
            'aliases', sa.ARRAY(sa.String()), server_default='{}', nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gcnevents', 'aliases')
    # ### end Alembic commands ###
