"""GCN aliases migration

Revision ID: 82e469da5fe9
Revises: 765363c68b5b
Create Date: 2022-10-30 10:30:00.357878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '82e469da5fe9'
down_revision = '765363c68b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'gcnevents',
        sa.Column(
            'aliases', sa.ARRAY(sa.String()), server_default='{}', nullable=False
        ),
    )
    op.add_column(
        'gcnevents',
        sa.Column('tach_id', sa.String(), nullable=True),
    )
    op.add_column(
        'gcnevents',
        sa.Column(
            'circulars',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{}',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gcnevents', 'circulars')
    op.drop_column('gcnevents', 'tach_id')
    op.drop_column('gcnevents', 'aliases')
    # ### end Alembic commands ###
