"""combined_plans

Revision ID: 849e70f9a857
Revises: 42f18fbf914d
Create Date: 2023-07-20 10:49:13.175676

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "849e70f9a857"
down_revision = "42f18fbf914d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observationplanrequests", sa.Column("combined_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observationplanrequests", "combined_id")
    # ### end Alembic commands ###
