"""GCN status explaination migration

Revision ID: 85e5b0be85a2
Revises: 43306550c9d0
Create Date: 2022-11-15 23:59:56.079390

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "85e5b0be85a2"
down_revision = "43306550c9d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sourcesconfirmedingcns", sa.Column("explaination", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sourcesconfirmedingcns", "explaination")
    # ### end Alembic commands ###
