"""shift replacement

Revision ID: 8acd303bd097
Revises: 8ec1cf68e06f
Create Date: 2022-05-19 01:12:47.537232

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8acd303bd097'
down_revision = '8ec1cf68e06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'shift_users',
        sa.Column(
            'needs_replacement', sa.Boolean(), nullable=False, server_default='False'
        ),
    )
    op.execute(
        """
alter table "public"."shift_users" alter column "needs_replacement" drop default;
"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_users', 'needs_replacement')
    # ### end Alembic commands ###
