"""gcn_tach

Revision ID: 8bd7883f99bd
Revises: f870b311df53
Create Date: 2022-11-18 15:24:35.704491

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "8bd7883f99bd"
down_revision = "f870b311df53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gcnevents",
        sa.Column(
            "aliases", sa.ARRAY(sa.String()), server_default="{}", nullable=False
        ),
    )
    op.add_column(
        "gcnevents",
        sa.Column("tach_id", sa.String(), nullable=True),
    )
    op.add_column(
        "gcnevents",
        sa.Column(
            "circulars",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gcnevents", "circulars")
    op.drop_column("gcnevents", "tach_id")
    op.drop_column("gcnevents", "aliases")
    # ### end Alembic commands ###
