"""Unique user token name

Revision ID: 8c018b9bf1c9
Revises: 89f08da6e93f
Create Date: 2022-01-13 09:15:30.639260

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '8c018b9bf1c9'
down_revision = '89f08da6e93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tokens_name_key', 'tokens', type_='unique')
    op.create_unique_constraint(
        'token_name_userid_unique_constraint', 'tokens', ['created_by_id', 'name']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_name_userid_unique_constraint', 'tokens', type_='unique')
    op.create_unique_constraint('tokens_name_key', 'tokens', ['name'])
    # ### end Alembic commands ###
