"""NICER TOO migration

Revision ID: 8e0f15cb11af
Revises: 831be4c27aef
Create Date: 2022-09-15 00:12:44.308601

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8e0f15cb11af"
down_revision = "831be4c27aef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'nicerxti'")
        op.execute("ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'NICERAPI'")

        op.execute(
            """
alter type "public"."followup_apis" rename to "followup_apis__old_version_to_be_dropped";

create type "public"."followup_apis" as enum ('ATLASAPI', 'KAITAPI', 'SEDMAPI', 'SEDMV2API', 'IOOAPI', 'IOIAPI', 'SPRATAPI', 'SINISTROAPI', 'SPECTRALAPI', 'FLOYDSAPI', 'MUSCATAPI', 'NICERAPI', 'MMAAPI', 'PS1API', 'SLACKAPI', 'UVOTXRTAPI', 'UVOTXRTMMAAPI', 'ZTFAPI', 'ZTFMMAAPI');

alter table "public"."instruments" alter column api_classname type "public"."followup_apis" using api_classname::text::"public"."followup_apis";

alter table "public"."instruments" alter column api_classname_obsplan type "public"."followup_apis" using api_classname_obsplan::text::"public"."followup_apis";

drop type "public"."followup_apis__old_version_to_be_dropped";
"""
        )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
