"""Queued observations

Revision ID: 8ec1cf68e06f
Revises: 64c2fee9d302
Create Date: 2022-05-05 17:40:54.445548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec1cf68e06f'
down_revision = '64c2fee9d302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'queuedobservations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('instrument_id', sa.Integer(), nullable=False),
        sa.Column('instrument_field_id', sa.Integer(), nullable=False),
        sa.Column('queue_name', sa.String(), nullable=True),
        sa.Column('obstime', sa.DateTime(), nullable=True),
        sa.Column('validity_window_start', sa.DateTime(), nullable=True),
        sa.Column('validity_window_end', sa.DateTime(), nullable=True),
        sa.Column('filt', sa.String(), nullable=True),
        sa.Column('exposure_time', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['instrument_field_id'], ['instrumentfields.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['instrument_id'], ['instruments.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', 'instrument_field_id'),
    )
    op.create_index(
        op.f('ix_queuedobservations_created_at'),
        'queuedobservations',
        ['created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_queuedobservations_created_at'), table_name='queuedobservations'
    )
    op.drop_table('queuedobservations')
    # ### end Alembic commands ###
