"""Adding new table for the source tag feature

Revision ID: 9239216843f5
Revises: 7eab209f29d3
Create Date: 2025-04-29 15:06:50.457833

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9239216843f5'
down_revision = '7eab209f29d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'objtagoptions',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_index(
        op.f('ix_objtagoptions_created_at'),
        'objtagoptions',
        ['created_at'],
        unique=False,
    )
    op.create_table(
        'obj_tag',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('obj_id', sa.String(), nullable=False),
        sa.Column('objtagoption_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['obj_id'], ['objs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['objtagoption_id'], ['objtagoptions.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_obj_tag_created_at'), 'obj_tag', ['created_at'], unique=False
    )
    op.create_index(
        'obj_tag_forward_ind', 'obj_tag', ['obj_id', 'objtagoption_id'], unique=True
    )
    op.create_index(
        'obj_tag_reverse_ind', 'obj_tag', ['objtagoption_id', 'obj_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('obj_tag_reverse_ind', table_name='obj_tag')
    op.drop_index('obj_tag_forward_ind', table_name='obj_tag')
    op.drop_index(op.f('ix_obj_tag_created_at'), table_name='obj_tag')
    op.drop_table('obj_tag')
    op.drop_index(op.f('ix_objtagoptions_created_at'), table_name='objtagoptions')
    op.drop_table('objtagoptions')
    # ### end Alembic commands ###
