"""TAROT migration

Revision ID: 94f87495c701
Revises: ce87ed8ca4b5
Create Date: 2024-07-17 19:41:49.085865

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "94f87495c701"
down_revision = "ce87ed8ca4b5"
branch_labels = None
depends_on = None


def upgrade():
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'TAROTAPI' AFTER 'UVOTXRTMMAAPI'"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
