"""New scanning report page

Revision ID: 9651f885731d
Revises: 1593df0c0979
Create Date: 2025-02-21 11:31:48.346254

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9651f885731d"
down_revision = "1593df0c0979"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidatescanreports",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("scanner", sa.String(), nullable=False),
        sa.Column("obj_id", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("already_classified", sa.Boolean(), nullable=True),
        sa.Column("host_redshift", sa.Float(), nullable=True),
        sa.Column("current_mag", sa.Float(), nullable=True),
        sa.Column("current_age", sa.Float(), nullable=True),
        sa.Column("forced_photometry_requested", sa.Boolean(), nullable=True),
        sa.Column("saver_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["obj_id"], ["objs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["saver_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidatescanreports_created_at"),
        "candidatescanreports",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_candidatescanreports_created_at"), table_name="candidatescanreports"
    )
    op.drop_table("candidatescanreports")
    # ### end Alembic commands ###
