"""Add public source page table

Revision ID: 96f23f9a4216
Revises: 94c30396a122
Create Date: 2024-05-20 21:05:25.190177

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96f23f9a4216'
down_revision = '94c30396a122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'publicsourcepages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.String(), nullable=False),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('hash', sa.String(), nullable=False),
        sa.Column('is_visible', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_publicsourcepages_created_at'),
        'publicsourcepages',
        ['created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_publicsourcepages_created_at'), table_name='publicsourcepages'
    )
    op.drop_table('publicsourcepages')
    # ### end Alembic commands ###
