"""sncosmo 2.10.0 migration

Revision ID: 97266d7af6e7
Revises: 47d84da106c4
Create Date: 2023-05-01 16:54:02.130267

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "97266d7af6e7"
down_revision = "47d84da106c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'tess' AFTER 'gaia::grvs'"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
