"""comments_attachments_on_disk

Revision ID: 99c470d77682
Revises: 1bf960dd68db
Create Date: 2022-08-08 10:22:22.235085

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "99c470d77682"
down_revision = "1bf960dd68db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("_attachment_path", sa.String(), nullable=True))
    op.add_column(
        "comments_on_gcns", sa.Column("_attachment_path", sa.String(), nullable=True)
    )
    op.add_column(
        "comments_on_shifts", sa.Column("_attachment_path", sa.String(), nullable=True)
    )
    op.add_column(
        "comments_on_spectra", sa.Column("_attachment_path", sa.String(), nullable=True)
    )
    op.add_column(
        "comments_on_earthquakes",
        sa.Column("_attachment_path", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments_on_earthquakes", "_attachment_path")
    op.drop_column("comments_on_spectra", "_attachment_path")
    op.drop_column("comments_on_shifts", "_attachment_path")
    op.drop_column("comments_on_gcns", "_attachment_path")
    op.drop_column("comments", "_attachment_path")
    # ### end Alembic commands ###
