"""super_objs

Revision ID: 9a7b5f6aa515
Revises: 7678f8674917
Create Date: 2026-03-06 16:32:07.834708

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9a7b5f6aa515"
down_revision = "7678f8674917"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "super_objs",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_roid", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_super_objs_created_at"), "super_objs", ["created_at"], unique=False
    )
    op.create_table(
        "obj_to_super_obj",
        sa.Column("obj_id", sa.String(), nullable=False),
        sa.Column("super_obj_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["obj_id"], ["objs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["super_obj_id"], ["super_objs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "obj_id", "super_obj_id"),
    )
    op.create_index(
        op.f("ix_obj_to_super_obj_created_at"),
        "obj_to_super_obj",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_obj_to_super_obj_created_at"), table_name="obj_to_super_obj")
    op.drop_table("obj_to_super_obj")
    op.drop_index(op.f("ix_super_objs_created_at"), table_name="super_objs")
    op.drop_table("super_objs")
    # ### end Alembic commands ###
