"""spectrum type

Revision ID: 9ab475331549
Revises: b05b6c4d1a17
Create Date: 2021-09-29 14:13:34.563693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab475331549'
down_revision = 'b05b6c4d1a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spectra', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spectra', 'type')
    # ### end Alembic commands ###
