"""Add gin index to alias column

Revision ID: 9c486cfefdc6
Revises: 9f2a7c3e1b45
Create Date: 2026-01-12 14:34:39.530749

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '9c486cfefdc6'
down_revision = '9f2a7c3e1b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pg_trgm extension for trigram-based pattern matching
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')

    # Create GIN index with gin_trgm_ops operator class for efficient LIKE queries on array elements
    op.execute(
        'CREATE INDEX ix_objs_alias_gin ON objs USING gin (alias gin_trgm_ops)'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_objs_alias_gin', table_name='objs')
    # Note: We don't drop the pg_trgm extension as other tables might be using it
    # ### end Alembic commands ###
