"""GROWTH India migration

Revision ID: 9f2563d6c9b5
Revises: 9f6032c799a9
Create Date: 2022-12-12 20:38:41.151525

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '9f2563d6c9b5'
down_revision = '9f6032c799a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'GROWTHINDIAMMAAPI' AFTER 'ATLASAPI'"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
