"""Create NEWFIRM instrument API for followup

Revision ID: 9f2a7c3e1b45
Revises: b3e29f8c1a7d
Create Date: 2025-07-16 21:04:42.349448

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "9f2a7c3e1b45"
down_revision = "b3e29f8c1a7d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'NEWFIRMAPI'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
