"""Refactoring sources_confirmed_in_gcn model

Revision ID: 9f502037e121
Revises: 6f853af1e900
Create Date: 2025-06-25 10:07:10.722881

"""

import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "9f502037e121"
down_revision = "6f853af1e900"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sources_in_gcn_status_enum = postgresql.ENUM(
        "confirmed",
        "rejected",
        "ambiguous",
        "pending",
        name="sources_in_gcn_status",
        create_type=False,
    )
    sources_in_gcn_status_enum.create(op.get_bind(), checkfirst=True)

    op.rename_table("sourcesconfirmedingcns", "sourcesingcns")

    op.execute(
        "ALTER SEQUENCE sourcesconfirmedingcns_id_seq RENAME TO sourcesingcns_id_seq"
    )

    op.add_column(
        "sourcesingcns",
        sa.Column(
            "status",
            sources_in_gcn_status_enum,
            nullable=False,
            server_default="pending",
        ),
    )

    connection = op.get_bind()

    connection.execute(
        sa.text("""
        UPDATE sourcesingcns
        SET status = CASE
            WHEN confirmed = true THEN 'confirmed'::sources_in_gcn_status
            WHEN confirmed = false THEN 'rejected'::sources_in_gcn_status
            WHEN confirmed IS NULL THEN 'ambiguous'::sources_in_gcn_status
            ELSE 'pending'::sources_in_gcn_status
        END
        """)
    )

    op.drop_column("sourcesingcns", "confirmed")
    op.drop_index("ix_sourcesconfirmedingcns_confirmer_id", table_name="sourcesingcns")
    op.drop_index("ix_sourcesconfirmedingcns_created_at", table_name="sourcesingcns")
    op.drop_index("ix_sourcesconfirmedingcns_dateobs", table_name="sourcesingcns")
    op.drop_index("ix_sourcesconfirmedingcns_obj_id", table_name="sourcesingcns")
    op.create_index(
        op.f("ix_sourcesingcns_confirmer_id"),
        "sourcesingcns",
        ["confirmer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sourcesingcns_created_at"),
        "sourcesingcns",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sourcesingcns_dateobs"), "sourcesingcns", ["dateobs"], unique=False
    )
    op.create_index(
        op.f("ix_sourcesingcns_obj_id"), "sourcesingcns", ["obj_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sourcesingcns_obj_id"), table_name="sourcesingcns")
    op.drop_index(op.f("ix_sourcesingcns_dateobs"), table_name="sourcesingcns")
    op.drop_index(op.f("ix_sourcesingcns_created_at"), table_name="sourcesingcns")
    op.drop_index(op.f("ix_sourcesingcns_confirmer_id"), table_name="sourcesingcns")
    op.create_index(
        "ix_sourcesconfirmedingcns_obj_id", "sourcesingcns", ["obj_id"], unique=False
    )
    op.create_index(
        "ix_sourcesconfirmedingcns_dateobs", "sourcesingcns", ["dateobs"], unique=False
    )
    op.create_index(
        "ix_sourcesconfirmedingcns_created_at",
        "sourcesingcns",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_sourcesconfirmedingcns_confirmer_id",
        "sourcesingcns",
        ["confirmer_id"],
        unique=False,
    )

    op.add_column("sourcesingcns", sa.Column("confirmed", sa.Boolean(), nullable=True))

    connection = op.get_bind()
    connection.execute(
        sa.text("""
        UPDATE sourcesingcns
        SET confirmed = CASE
            WHEN status = 'confirmed' THEN true
            WHEN status = 'rejected' THEN false
            WHEN status = 'ambiguous' THEN NULL
            WHEN status = 'pending' THEN NULL
            ELSE NULL
        END
        """)
    )

    op.drop_column("sourcesingcns", "status")

    sources_in_gcn_status_enum = postgresql.ENUM(
        "confirmed", "rejected", "ambiguous", "pending", name="sources_in_gcn_status"
    )
    sources_in_gcn_status_enum.drop(op.get_bind(), checkfirst=True)

    op.execute(
        "ALTER SEQUENCE sourcesingcns_id_seq RENAME TO sourcesconfirmedingcns_id_seq"
    )

    op.rename_table("sourcesingcns", "sourcesconfirmedingcns")
    # ### end Alembic commands ###
