"""Generic API migration

Revision ID: 9f6032c799a9
Revises: 68a2e8e8e027
Create Date: 2022-12-11 20:10:58.651576

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "9f6032c799a9"
down_revision = "68a2e8e8e027"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'GENERICAPI' AFTER 'ATLASAPI'"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
