"""shift_comments

Revision ID: a1868013bebb
Revises: 8acd303bd097
Create Date: 2022-05-26 10:00:32.455132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1868013bebb'
down_revision = '8acd303bd097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'comments_on_shifts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('attachment_name', sa.String(), nullable=True),
        sa.Column('attachment_bytes', sa.LargeBinary(), nullable=True),
        sa.Column('origin', sa.String(), nullable=True),
        sa.Column('bot', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('shift_id', sa.Integer(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_comments_on_shifts_author_id'),
        'comments_on_shifts',
        ['author_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_comments_on_shifts_created_at'),
        'comments_on_shifts',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_comments_on_shifts_shift_id'),
        'comments_on_shifts',
        ['shift_id'],
        unique=False,
    )
    op.create_table(
        'group_comments_on_shifts',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('comments_on_shift_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['comments_on_shift_id'], ['comments_on_shifts.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'group_comments_on_shifts_forward_ind',
        'group_comments_on_shifts',
        ['group_id', 'comments_on_shift_id'],
        unique=True,
    )
    op.create_index(
        'group_comments_on_shifts_reverse_ind',
        'group_comments_on_shifts',
        ['comments_on_shift_id', 'group_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_group_comments_on_shifts_created_at'),
        'group_comments_on_shifts',
        ['created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_group_comments_on_shifts_created_at'),
        table_name='group_comments_on_shifts',
    )
    op.drop_index(
        'group_comments_on_shifts_reverse_ind', table_name='group_comments_on_shifts'
    )
    op.drop_index(
        'group_comments_on_shifts_forward_ind', table_name='group_comments_on_shifts'
    )
    op.drop_table('group_comments_on_shifts')
    op.drop_index(
        op.f('ix_comments_on_shifts_shift_id'), table_name='comments_on_shifts'
    )
    op.drop_index(
        op.f('ix_comments_on_shifts_created_at'), table_name='comments_on_shifts'
    )
    op.drop_index(
        op.f('ix_comments_on_shifts_author_id'), table_name='comments_on_shifts'
    )
    op.drop_table('comments_on_shifts')
    # ### end Alembic commands ###
