"""SOAR migration

Revision ID: a4fd59613f77
Revises: 7b0d2b1b6561
Create Date: 2024-05-17 19:15:08.191322

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a4fd59613f77"
down_revision = "7b0d2b1b6561"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
alter type "public"."followup_apis" rename to "followup_apis__old_version_to_be_dropped";

create type "public"."followup_apis" as enum ('MMAAPI', 'GENERICAPI', 'SLACKAPI', 'ATLASAPI', 'GROWTHINDIAMMAAPI', 'KAITAPI', 'SEDMAPI', 'SEDMV2API', 'IOOAPI', 'IOIAPI', 'SPRATAPI', 'SINISTROAPI', 'SPECTRALAPI', 'FLOYDSAPI', 'MUSCATAPI', 'NICERAPI', 'PS1API', 'SOARGHTSAPI', 'SOARGHTSIMAGERAPI', 'SOARTSPECAPI', 'UVOTXRTAPI', 'UVOTXRTMMAAPI', 'TESSAPI', 'TRTAPI', 'WINTERAPI', 'ZTFAPI', 'ZTFMMAAPI');

alter table "public"."instruments" alter column api_classname type "public"."followup_apis" using api_classname::text::"public"."followup_apis";

alter table "public"."instruments" alter column api_classname_obsplan type "public"."followup_apis" using api_classname_obsplan::text::"public"."followup_apis";

drop type "public"."followup_apis__old_version_to_be_dropped";
    """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
