"""Observation and galaxy index migration

Revision ID: a75237f48f29
Revises: a936f994d65c
Create Date: 2022-06-17 07:49:47.289551

"""

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a75237f48f29"
down_revision = "a936f994d65c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "executedobservations",
        "obstime",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.create_index(
        op.f("ix_executedobservations_obstime"),
        "executedobservations",
        ["obstime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_galaxys_catalog_name"), "galaxys", ["catalog_name"], unique=False
    )
    op.alter_column(
        "queuedobservations",
        "obstime",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.create_index(
        op.f("ix_queuedobservations_obstime"),
        "queuedobservations",
        ["obstime"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_queuedobservations_obstime"), table_name="queuedobservations"
    )
    op.alter_column(
        "queuedobservations",
        "obstime",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_index(op.f("ix_galaxys_catalog_name"), table_name="galaxys")
    op.drop_index(
        op.f("ix_executedobservations_obstime"), table_name="executedobservations"
    )
    op.alter_column(
        "executedobservations",
        "obstime",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###
