"""executed observations migration

Revision ID: a8318144625d
Revises: 97266d7af6e7
Create Date: 2023-05-02 12:27:55.855196

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a8318144625d"
down_revision = "97266d7af6e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_executedobservations_instrument_field_id"),
        "executedobservations",
        ["instrument_field_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executedobservations_instrument_id"),
        "executedobservations",
        ["instrument_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_executedobservations_instrument_id"), table_name="executedobservations"
    )
    op.drop_index(
        op.f("ix_executedobservations_instrument_field_id"),
        table_name="executedobservations",
    )
    # ### end Alembic commands ###
