"""Galaxy page migration

Revision ID: a936f994d65c
Revises: d175da67db16
Create Date: 2022-06-17 15:04:48.298481

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a936f994d65c"
down_revision = "d175da67db16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "galaxys", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "galaxys", type_="unique")
    # ### end Alembic commands ###
