"""user_bio_and_bot

Revision ID: aa6432209e3e
Revises: 77c4af61eea6
Create Date: 2024-05-07 15:39:21.303613

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aa6432209e3e"
down_revision = "77c4af61eea6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("bio", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("is_bot", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_bot")
    op.drop_column("users", "bio")
    # ### end Alembic commands ###
