"""ShiftUsers

Revision ID: ad1628fa17f1
Revises: 7c4ffd3821ba
Create Date: 2022-03-15 18:56:17.202353

"""

# revision identifiers, used by Alembic.
revision = 'ad1628fa17f1'
down_revision = '7c4ffd3821ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
