"""Photometry validation migration

Revision ID: af970c6b6b3c
Revises: 550fbafe6a2c
Create Date: 2024-03-02 00:12:53.315651

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af970c6b6b3c'
down_revision = '550fbafe6a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'photometryvalidations',
        sa.Column('photometry_id', sa.Integer(), nullable=False),
        sa.Column('validated', sa.Boolean(), nullable=True),
        sa.Column('validator_id', sa.Integer(), nullable=False),
        sa.Column('explanation', sa.String(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['photometry_id'], ['photometry.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['validator_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_photometryvalidations_created_at'),
        'photometryvalidations',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_photometryvalidations_photometry_id'),
        'photometryvalidations',
        ['photometry_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_photometryvalidations_validator_id'),
        'photometryvalidations',
        ['validator_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_photometryvalidations_validator_id'),
        table_name='photometryvalidations',
    )
    op.drop_index(
        op.f('ix_photometryvalidations_photometry_id'),
        table_name='photometryvalidations',
    )
    op.drop_index(
        op.f('ix_photometryvalidations_created_at'), table_name='photometryvalidations'
    )
    op.drop_table('photometryvalidations')
    # ### end Alembic commands ###
