"""event advocate migration

Revision ID: b0f0b2a30357
Revises: ce87ed8ca4b5
Create Date: 2024-07-04 18:58:29.493558

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f0b2a30357'
down_revision = 'ce87ed8ca4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gcnevent_users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('gcnevent_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['gcnevent_id'], ['gcnevents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'gcnevent_users_forward_ind',
        'gcnevent_users',
        ['gcnevent_id', 'user_id'],
        unique=True,
    )
    op.create_index(
        'gcnevent_users_reverse_ind',
        'gcnevent_users',
        ['user_id', 'gcnevent_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_gcnevent_users_created_at'),
        'gcnevent_users',
        ['created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gcnevent_users_created_at'), table_name='gcnevent_users')
    op.drop_index('gcnevent_users_reverse_ind', table_name='gcnevent_users')
    op.drop_index('gcnevent_users_forward_ind', table_name='gcnevent_users')
    op.drop_table('gcnevent_users')
    # ### end Alembic commands ###
