"""TESS alerts migration

Revision ID: b2aadcb864d1
Revises: cdfb7edc7438
Create Date: 2023-05-27 15:27:13.327228

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b2aadcb864d1"
down_revision = "cdfb7edc7438"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'TESSAPI' AFTER 'UVOTXRTMMAAPI'"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
