"""Add classification origin

Revision ID: b5a2ca2952e3
Revises: b2aadcb864d1
Create Date: 2023-05-30 15:39:18.447186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a2ca2952e3'
down_revision = 'b2aadcb864d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifications', sa.Column('origin', sa.String(), nullable=True))
    op.create_index(
        op.f('ix_classifications_origin'), 'classifications', ['origin'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_origin'), table_name='classifications')
    op.drop_column('classifications', 'origin')
    # ### end Alembic commands ###
