"""moving object migration

Revision ID: b623936b0187
Revises: 96f23f9a4216
Create Date: 2024-06-07 15:18:29.885734

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b623936b0187'
down_revision = '96f23f9a4216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'moving_objects',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('mjd', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('ra', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('dec', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('ra_err', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('dec_err', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_moving_objects_created_at'),
        'moving_objects',
        ['created_at'],
        unique=False,
    )
    op.create_table(
        'moving_object_associations',
        sa.Column('moving_object_id', sa.String(), nullable=False),
        sa.Column('obj_id', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['moving_object_id'], ['moving_objects.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['obj_id'], ['objs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('moving_object_id', 'obj_id', 'id'),
    )
    op.create_index(
        op.f('ix_moving_object_associations_created_at'),
        'moving_object_associations',
        ['created_at'],
        unique=False,
    )
    op.add_column(
        'eventobservationplans',
        sa.Column('moving_object_id', sa.String(), nullable=True),
    )
    op.alter_column(
        'eventobservationplans',
        'dateobs',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.create_index(
        op.f('ix_eventobservationplans_moving_object_id'),
        'eventobservationplans',
        ['moving_object_id'],
        unique=False,
    )
    op.create_foreign_key(
        None,
        'eventobservationplans',
        'moving_objects',
        ['moving_object_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.add_column(
        'localizations', sa.Column('moving_object_id', sa.String(), nullable=True)
    )
    op.alter_column(
        'localizations', 'dateobs', existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.create_index(
        op.f('ix_localizations_moving_object_id'),
        'localizations',
        ['moving_object_id'],
        unique=False,
    )
    op.create_foreign_key(
        None,
        'localizations',
        'moving_objects',
        ['moving_object_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.add_column(
        'observationplanrequests',
        sa.Column('moving_object_id', sa.String(), nullable=True),
    )
    op.alter_column(
        'observationplanrequests',
        'gcnevent_id',
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.create_index(
        op.f('ix_observationplanrequests_moving_object_id'),
        'observationplanrequests',
        ['moving_object_id'],
        unique=False,
    )
    op.create_foreign_key(
        None,
        'observationplanrequests',
        'moving_objects',
        ['moving_object_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.add_column(
        'plannedobservations', sa.Column('moving_object_id', sa.String(), nullable=True)
    )
    op.alter_column(
        'plannedobservations',
        'dateobs',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.create_index(
        op.f('ix_plannedobservations_moving_object_id'),
        'plannedobservations',
        ['moving_object_id'],
        unique=False,
    )
    op.create_foreign_key(
        None,
        'plannedobservations',
        'moving_objects',
        ['moving_object_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plannedobservations', type_='foreignkey')
    op.drop_index(
        op.f('ix_plannedobservations_moving_object_id'),
        table_name='plannedobservations',
    )
    op.alter_column(
        'plannedobservations',
        'dateobs',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_column('plannedobservations', 'moving_object_id')
    op.drop_constraint(None, 'observationplanrequests', type_='foreignkey')
    op.drop_index(
        op.f('ix_observationplanrequests_moving_object_id'),
        table_name='observationplanrequests',
    )
    op.alter_column(
        'observationplanrequests',
        'gcnevent_id',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column('observationplanrequests', 'moving_object_id')
    op.drop_constraint(None, 'localizations', type_='foreignkey')
    op.drop_index(op.f('ix_localizations_moving_object_id'), table_name='localizations')
    op.alter_column(
        'localizations', 'dateobs', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_column('localizations', 'moving_object_id')
    op.drop_constraint(None, 'eventobservationplans', type_='foreignkey')
    op.drop_index(
        op.f('ix_eventobservationplans_moving_object_id'),
        table_name='eventobservationplans',
    )
    op.alter_column(
        'eventobservationplans',
        'dateobs',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_column('eventobservationplans', 'moving_object_id')
    op.drop_index(
        op.f('ix_moving_object_associations_created_at'),
        table_name='moving_object_associations',
    )
    op.drop_table('moving_object_associations')
    op.drop_index(op.f('ix_moving_objects_created_at'), table_name='moving_objects')
    op.drop_table('moving_objects')
    # ### end Alembic commands ###
