"""moving objects migration

Revision ID: c10a634f99f0
Revises: 96f23f9a4216
Create Date: 2024-06-03 16:40:50.711883

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c10a634f99f0'
down_revision = '96f23f9a4216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'moving_object',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('mjd', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('ra', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('dec', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('ra_err', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('dec_err', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('obj_ids', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_moving_object_created_at'),
        'moving_object',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_moving_object_name'), 'moving_object', ['name'], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moving_object_name'), table_name='moving_object')
    op.drop_index(op.f('ix_moving_object_created_at'), table_name='moving_object')
    op.drop_table('moving_object')
    # ### end Alembic commands ###
