"""Index created_at for all relevant models

Revision ID: c1354c411fab
Revises: 5365c004a923
Create Date: 2021-02-23 11:34:33.280876

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c1354c411fab"
down_revision = "5365c004a923"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_acls_created_at"), "acls", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_allocations_created_at"), "allocations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_created_at"), "annotations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_associations_created_at"), "associations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_candidates_created_at"), "candidates", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_classicalassignments_created_at"),
        "classicalassignments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classifications_created_at"),
        "classifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_codes_created_at"), "codes", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_comments_created_at"), "comments", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_cronjobruns_created_at"), "cronjobruns", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_filters_created_at"), "filters", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_followuprequests_created_at"),
        "followuprequests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_annotations_created_at"),
        "group_annotations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_classifications_created_at"),
        "group_classifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_comments_created_at"),
        "group_comments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_invitations_created_at"),
        "group_invitations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_notifications_created_at"),
        "group_notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_photometry_created_at"),
        "group_photometry",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_spectra_created_at"),
        "group_spectra",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_streams_created_at"),
        "group_streams",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_taxonomy_created_at"),
        "group_taxonomy",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_users_created_at"), "group_users", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_groupadmissionrequests_created_at"),
        "groupadmissionrequests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_groups_created_at"), "groups", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_instruments_created_at"), "instruments", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_invitations_created_at"), "invitations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_listings_created_at"), "listings", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_nonces_created_at"), "nonces", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_objs_created_at"), "objs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_observingruns_created_at"),
        "observingruns",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partials_created_at"), "partials", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_photometry_created_at"), "photometry", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_request_groups_created_at"),
        "request_groups",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_acls_created_at"), "role_acls", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_roles_created_at"), "roles", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_sourcenotifications_created_at"),
        "sourcenotifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sources_created_at"), "sources", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_spectra_created_at"), "spectra", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_spectrum_observers_created_at"),
        "spectrum_observers",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spectrum_reducers_created_at"),
        "spectrum_reducers",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stream_invitations_created_at"),
        "stream_invitations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stream_users_created_at"), "stream_users", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_streams_created_at"), "streams", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_taxonomies_created_at"), "taxonomies", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_telescopes_created_at"), "telescopes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_thumbnails_created_at"), "thumbnails", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_token_acls_created_at"), "token_acls", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_tokens_created_at"), "tokens", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_acls_created_at"), "user_acls", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_invitations_created_at"),
        "user_invitations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_roles_created_at"), "user_roles", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_usernotifications_created_at"),
        "usernotifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_usersocialauths_created_at"),
        "usersocialauths",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usersocialauths_created_at"), table_name="usersocialauths")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index(
        op.f("ix_usernotifications_created_at"), table_name="usernotifications"
    )
    op.drop_index(op.f("ix_user_roles_created_at"), table_name="user_roles")
    op.drop_index(op.f("ix_user_invitations_created_at"), table_name="user_invitations")
    op.drop_index(op.f("ix_user_acls_created_at"), table_name="user_acls")
    op.drop_index(op.f("ix_tokens_created_at"), table_name="tokens")
    op.drop_index(op.f("ix_token_acls_created_at"), table_name="token_acls")
    op.drop_index(op.f("ix_thumbnails_created_at"), table_name="thumbnails")
    op.drop_index(op.f("ix_telescopes_created_at"), table_name="telescopes")
    op.drop_index(op.f("ix_taxonomies_created_at"), table_name="taxonomies")
    op.drop_index(op.f("ix_streams_created_at"), table_name="streams")
    op.drop_index(op.f("ix_stream_users_created_at"), table_name="stream_users")
    op.drop_index(
        op.f("ix_stream_invitations_created_at"), table_name="stream_invitations"
    )
    op.drop_index(
        op.f("ix_spectrum_reducers_created_at"), table_name="spectrum_reducers"
    )
    op.drop_index(
        op.f("ix_spectrum_observers_created_at"), table_name="spectrum_observers"
    )
    op.drop_index(op.f("ix_spectra_created_at"), table_name="spectra")
    op.drop_index(op.f("ix_sources_created_at"), table_name="sources")
    op.drop_index(
        op.f("ix_sourcenotifications_created_at"), table_name="sourcenotifications"
    )
    op.drop_index(op.f("ix_roles_created_at"), table_name="roles")
    op.drop_index(op.f("ix_role_acls_created_at"), table_name="role_acls")
    op.drop_index(op.f("ix_request_groups_created_at"), table_name="request_groups")
    op.drop_index(op.f("ix_photometry_created_at"), table_name="photometry")
    op.drop_index(op.f("ix_partials_created_at"), table_name="partials")
    op.drop_index(op.f("ix_observingruns_created_at"), table_name="observingruns")
    op.drop_index(op.f("ix_objs_created_at"), table_name="objs")
    op.drop_index(op.f("ix_nonces_created_at"), table_name="nonces")
    op.drop_index(op.f("ix_listings_created_at"), table_name="listings")
    op.drop_index(op.f("ix_invitations_created_at"), table_name="invitations")
    op.drop_index(op.f("ix_instruments_created_at"), table_name="instruments")
    op.drop_index(op.f("ix_groups_created_at"), table_name="groups")
    op.drop_index(
        op.f("ix_groupadmissionrequests_created_at"),
        table_name="groupadmissionrequests",
    )
    op.drop_index(op.f("ix_group_users_created_at"), table_name="group_users")
    op.drop_index(op.f("ix_group_taxonomy_created_at"), table_name="group_taxonomy")
    op.drop_index(op.f("ix_group_streams_created_at"), table_name="group_streams")
    op.drop_index(op.f("ix_group_spectra_created_at"), table_name="group_spectra")
    op.drop_index(op.f("ix_group_photometry_created_at"), table_name="group_photometry")
    op.drop_index(
        op.f("ix_group_notifications_created_at"), table_name="group_notifications"
    )
    op.drop_index(
        op.f("ix_group_invitations_created_at"), table_name="group_invitations"
    )
    op.drop_index(op.f("ix_group_comments_created_at"), table_name="group_comments")
    op.drop_index(
        op.f("ix_group_classifications_created_at"), table_name="group_classifications"
    )
    op.drop_index(
        op.f("ix_group_annotations_created_at"), table_name="group_annotations"
    )
    op.drop_index(op.f("ix_followuprequests_created_at"), table_name="followuprequests")
    op.drop_index(op.f("ix_filters_created_at"), table_name="filters")
    op.drop_index(op.f("ix_cronjobruns_created_at"), table_name="cronjobruns")
    op.drop_index(op.f("ix_comments_created_at"), table_name="comments")
    op.drop_index(op.f("ix_codes_created_at"), table_name="codes")
    op.drop_index(op.f("ix_classifications_created_at"), table_name="classifications")
    op.drop_index(
        op.f("ix_classicalassignments_created_at"), table_name="classicalassignments"
    )
    op.drop_index(op.f("ix_candidates_created_at"), table_name="candidates")
    op.drop_index(op.f("ix_associations_created_at"), table_name="associations")
    op.drop_index(op.f("ix_annotations_created_at"), table_name="annotations")
    op.drop_index(op.f("ix_allocations_created_at"), table_name="allocations")
    op.drop_index(op.f("ix_acls_created_at"), table_name="acls")
    # ### end Alembic commands ###
