"""Add colors to sources tags

Revision ID: c3ee8a0c8d51
Revises: 6f853af1e900
Create Date: 2025-06-27 15:39:14.084598

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "c3ee8a0c8d51"
down_revision = "6f853af1e900"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "objtagoptions", sa.Column("color", sa.String(length=7), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objtagoptions", "color")
    # ### end Alembic commands ###
