"""swiftxrt migration

Revision ID: c589cb7d70ec
Revises: fff290c02ef8
Create Date: 2022-09-10 00:41:18.995925

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c589cb7d70ec"
down_revision = "fff290c02ef8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'swiftxrt' AFTER '2massks'"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
