"""Create NGPS instrument API for followup

Revision ID: c7d1a4e9f3b2
Revises: b7e1f4a90c31
Create Date: 2026-08-11 00:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c7d1a4e9f3b2"
down_revision = "a4d17c3b8e52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'NGPSAPI'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
