"""swift enum

Revision ID: ca2e59a85ff4
Revises: 33ef976ca10f
Create Date: 2022-03-04 07:15:40.511218

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "ca2e59a85ff4"
down_revision = "33ef976ca10f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE followup_apis ADD VALUE IF NOT EXISTS 'UVOTXRTAPI' AFTER 'SLACKAPI'"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
