"""allocation_types

Revision ID: cd65935c6d98
Revises: 5516eb897b1c
Create Date: 2023-10-24 10:57:29.587162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from skyportal.enum_types import ALLOWED_ALLOCATION_TYPES

# revision identifiers, used by Alembic.
revision = 'cd65935c6d98'
down_revision = '5516eb897b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f'''
        DO $$ BEGIN
          CREATE TYPE "allocationtypes" AS ENUM ({', '.join(f"'{t}'" for t in ALLOWED_ALLOCATION_TYPES)} );
        EXCEPTION
          WHEN duplicate_object THEN null;
        END $$;
        '''
    )

    op.add_column(
        'allocations',
        sa.Column(
            'types',
            postgresql.ARRAY(
                sa.Enum(
                    *ALLOWED_ALLOCATION_TYPES,
                    name='allocationtypes',
                )
            ),
            server_default=sa.text("'{" + ALLOWED_ALLOCATION_TYPES[0] + "}'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allocations', 'types')
    # ### end Alembic commands ###
