"""Test migration

Revision ID: cdc34ec7de34
Revises: 1c2d593e9778
Create Date: 2021-02-17 13:55:18.300172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc34ec7de34'
down_revision = '1c2d593e9778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telescopes', sa.Column('test', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telescopes', 'test')
    # ### end Alembic commands ###
