"""Automatically publish source when created

Revision ID: d05256bc14ed
Revises: 3eb663b5c3e0
Create Date: 2025-01-15 16:55:03.008848

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05256bc14ed'
down_revision = '3eb663b5c3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'publicreleases',
        sa.Column('automatically_publish', sa.Boolean(), nullable=False),
    )
    op.add_column(
        'publicsourcepages',
        sa.Column('auto_publish', sa.Boolean(), server_default='false', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicsourcepages', 'auto_publish')
    op.drop_column('publicreleases', 'automatically_publish')
    # ### end Alembic commands ###
