"""GCN summary migration

Revision ID: d0a5f8e4bac4
Revises: e10fa2a9e71d
Create Date: 2023-01-08 08:03:55.805877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a5f8e4bac4'
down_revision = 'e10fa2a9e71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gcnsummarys',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('sent_by_id', sa.Integer(), nullable=False),
        sa.Column('dateobs', sa.DateTime(), nullable=False),
        sa.Column('text', sa.Unicode(), nullable=False),
        sa.ForeignKeyConstraint(['dateobs'], ['gcnevents.dateobs'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_gcnsummarys_created_at'), 'gcnsummarys', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_gcnsummarys_dateobs'), 'gcnsummarys', ['dateobs'], unique=False
    )
    op.create_index(
        op.f('ix_gcnsummarys_sent_by_id'), 'gcnsummarys', ['sent_by_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gcnsummarys_sent_by_id'), table_name='gcnsummarys')
    op.drop_index(op.f('ix_gcnsummarys_dateobs'), table_name='gcnsummarys')
    op.drop_index(op.f('ix_gcnsummarys_created_at'), table_name='gcnsummarys')
    op.drop_table('gcnsummarys')
    # ### end Alembic commands ###
