"""add_allocation_validity_range

Revision ID: d10af879495e
Revises: b3e29f8c1a7d
Create Date: 2025-07-30 12:46:00.552248

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d10af879495e"
down_revision = "b3e29f8c1a7d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # drop start_date and end_date value and create empty validity_ranges
    op.drop_column("allocations", "start_date")
    op.drop_column("allocations", "end_date")
    op.add_column(
        "allocations",
        sa.Column(
            "validity_ranges", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocations",
        sa.Column(
            "start_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "allocations",
        sa.Column(
            "end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )

    op.drop_column("allocations", "validity_ranges")
    # ### end Alembic commands ###
