"""Adding new table for the source tag feature

Revision ID: d2ab4a302b57
Revises: 7eab209f29d3
Create Date: 2025-04-28 16:18:22.516878

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd2ab4a302b57'
down_revision = '7eab209f29d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
