"""Localization attachments migration

Revision ID: d2fadb29175f
Revises: 2eb1e05411c5
Create Date: 2023-04-09 19:24:23.734163

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d2fadb29175f"
down_revision = "2eb1e05411c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "localizations", sa.Column("_localization_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("localizations", "_localization_path")
    # ### end Alembic commands ###
