import healpix_alchemy

"""crossmatch

Revision ID: d61a8bea7313
Revises: f9611048498a
Create Date: 2022-01-20 18:07:31.406886

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d61a8bea7313"
down_revision = "f9611048498a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "localizationtiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("localization_id", sa.Integer(), nullable=False),
        sa.Column("probdensity", sa.Float(), nullable=False),
        sa.Column("healpix", healpix_alchemy.types.Tile(), nullable=False),
        sa.ForeignKeyConstraint(
            ["localization_id"], ["localizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "localization_id", "healpix"),
    )
    op.create_index(
        op.f("ix_localizationtiles_created_at"),
        "localizationtiles",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_localizationtiles_healpix"),
        "localizationtiles",
        ["healpix"],
        unique=False,
        postgresql_using="spgist",
    )
    op.add_column(
        "objs", sa.Column("healpix", healpix_alchemy.types.Point(), nullable=True)
    )
    op.create_index(op.f("ix_objs_healpix"), "objs", ["healpix"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_objs_healpix"), table_name="objs")
    op.drop_column("objs", "healpix")
    op.drop_index(
        op.f("ix_localizationtiles_healpix"),
        table_name="localizationtiles",
        postgresql_using="spgist",
    )
    op.drop_index(
        op.f("ix_localizationtiles_created_at"), table_name="localizationtiles"
    )
    op.drop_table("localizationtiles")
    # ### end Alembic commands ###
