"""atlas api

Revision ID: d6b24747693a
Revises: 695affb5e503
Create Date: 2022-02-17 17:23:25.162577

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d6b24747693a"
down_revision = "695affb5e503"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
alter type "public"."followup_apis" rename to "followup_apis__old_version_to_be_dropped";

create type "public"."followup_apis" as enum ('ATLASAPI', 'KAITAPI', 'SEDMAPI', 'SEDMV2API', 'IOOAPI', 'IOIAPI', 'SPRATAPI', 'SINISTROAPI', 'SPECTRALAPI', 'FLOYDSAPI', 'MUSCATAPI', 'MMAAPI', 'SLACKAPI', 'ZTFAPI', 'ZTFMMAAPI');

alter table "public"."instruments" alter column api_classname type "public"."followup_apis" using api_classname::text::"public"."followup_apis";

alter table "public"."instruments" alter column api_classname_obsplan type "public"."followup_apis" using api_classname_obsplan::text::"public"."followup_apis";

drop type "public"."followup_apis__old_version_to_be_dropped";
"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
