"""treasuremap

Revision ID: dc7f29329a89
Revises: 6a769fd6d909
Create Date: 2022-02-23 10:29:01.434260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7f29329a89'
down_revision = '6a769fd6d909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'instruments', sa.Column('treasuremap_id', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'treasuremap_id')
    # ### end Alembic commands ###
