"""fields migration

Revision ID: e1792014851a
Revises: 171e9ea18885
Create Date: 2021-08-24 10:18:27.997155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1792014851a'
down_revision = '171e9ea18885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'instrumentfields',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('instrument_id', sa.Integer(), nullable=False),
        sa.Column('field_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['instrument_id'], ['instruments.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_instrumentfields_created_at'),
        'instrumentfields',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_instrumentfields_field_id'),
        'instrumentfields',
        ['field_id'],
        unique=False,
    )
    op.create_table(
        'instrumentfieldtiles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('nested_lo', sa.BigInteger(), nullable=False),
        sa.Column('nested_hi', sa.BigInteger(), nullable=False),
        sa.Column('instrument_id', sa.Integer(), nullable=False),
        sa.Column('instrument_field_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['instrument_field_id'], ['instrumentfields.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['instrument_id'], ['instruments.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', 'nested_lo'),
    )
    op.create_index(
        op.f('ix_instrumentfieldtiles_created_at'),
        'instrumentfieldtiles',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_instrumentfieldtiles_nested_lo'),
        'instrumentfieldtiles',
        ['nested_lo'],
        unique=False,
    )
    op.add_column('objs', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('objs', sa.Column('y', sa.Float(), nullable=True))
    op.add_column('objs', sa.Column('z', sa.Float(), nullable=True))
    op.add_column('objs', sa.Column('nested', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_objs_nested'), 'objs', ['nested'], unique=False)
    op.create_index('ix_objs_point', 'objs', ['x', 'y', 'z'], unique=False)
    op.add_column('photometry', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('photometry', sa.Column('y', sa.Float(), nullable=True))
    op.add_column('photometry', sa.Column('z', sa.Float(), nullable=True))
    op.add_column('photometry', sa.Column('nested', sa.BigInteger(), nullable=True))
    op.create_index(
        op.f('ix_photometry_nested'), 'photometry', ['nested'], unique=False
    )
    op.create_index('ix_photometry_point', 'photometry', ['x', 'y', 'z'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photometry_point', table_name='photometry')
    op.drop_index(op.f('ix_photometry_nested'), table_name='photometry')
    op.drop_column('photometry', 'nested')
    op.drop_column('photometry', 'z')
    op.drop_column('photometry', 'y')
    op.drop_column('photometry', 'x')
    op.drop_index('ix_objs_point', table_name='objs')
    op.drop_index(op.f('ix_objs_nested'), table_name='objs')
    op.drop_column('objs', 'nested')
    op.drop_column('objs', 'z')
    op.drop_column('objs', 'y')
    op.drop_column('objs', 'x')
    op.drop_index(
        op.f('ix_instrumentfieldtiles_nested_lo'), table_name='instrumentfieldtiles'
    )
    op.drop_index(
        op.f('ix_instrumentfieldtiles_created_at'), table_name='instrumentfieldtiles'
    )
    op.drop_table('instrumentfieldtiles')
    op.drop_index(op.f('ix_instrumentfields_field_id'), table_name='instrumentfields')
    op.drop_index(op.f('ix_instrumentfields_created_at'), table_name='instrumentfields')
    op.drop_table('instrumentfields')
    # ### end Alembic commands ###
