"""Add classification origin

Revision ID: e2273768afa4
Revises: 0e9932f8b83e
Create Date: 2023-05-31 10:36:42.387023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2273768afa4'
down_revision = '0e9932f8b83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifications', sa.Column('origin', sa.String(), nullable=True))
    op.create_index(
        op.f('ix_classifications_origin'), 'classifications', ['origin'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_origin'), table_name='classifications')
    op.drop_column('classifications', 'origin')
    # ### end Alembic commands ###
