"""default_analysis

Revision ID: e268e17ca352
Revises: c276f6343274
Create Date: 2023-02-17 14:30:24.725925

"""

import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e268e17ca352"
down_revision = "c276f6343274"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_analyses",
        sa.Column("analysis_service_id", sa.Integer(), nullable=False),
        sa.Column("show_parameters", sa.Boolean(), nullable=False),
        sa.Column("show_plots", sa.Boolean(), nullable=False),
        sa.Column("show_corner", sa.Boolean(), nullable=False),
        sa.Column(
            "default_analysis_parameters",
            sqlalchemy_utils.types.json.JSONType(),
            nullable=True,
        ),
        sa.Column(
            "source_filter", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_service_id"], ["analysis_services.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_default_analyses_analysis_service_id"),
        "default_analyses",
        ["analysis_service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_default_analyses_author_id"),
        "default_analyses",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_default_analyses_created_at"),
        "default_analyses",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "group_default_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("default_analyse_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_analyse_id"], ["default_analyses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "group_default_analyses_forward_ind",
        "group_default_analyses",
        ["group_id", "default_analyse_id"],
        unique=True,
    )
    op.create_index(
        "group_default_analyses_reverse_ind",
        "group_default_analyses",
        ["default_analyse_id", "group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_default_analyses_created_at"),
        "group_default_analyses",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_group_default_analyses_created_at"),
        table_name="group_default_analyses",
    )
    op.drop_index(
        "group_default_analyses_reverse_ind", table_name="group_default_analyses"
    )
    op.drop_index(
        "group_default_analyses_forward_ind", table_name="group_default_analyses"
    )
    op.drop_table("group_default_analyses")
    op.drop_index(op.f("ix_default_analyses_created_at"), table_name="default_analyses")
    op.drop_index(op.f("ix_default_analyses_author_id"), table_name="default_analyses")
    op.drop_index(
        op.f("ix_default_analyses_analysis_service_id"), table_name="default_analyses"
    )
    op.drop_table("default_analyses")
    # ### end Alembic commands ###
