"""Add can_save column to GroupUser table

Revision ID: e4cfcff820c5
Revises: 2f390f5dc944
Create Date: 2021-05-24 13:43:44.161080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cfcff820c5'
down_revision = '2f390f5dc944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'group_users',
        sa.Column('can_save', sa.Boolean(), server_default='true', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_users', 'can_save')
    # ### end Alembic commands ###
