"""moving_objects

Revision ID: e5054d9881e4
Revises: 96f23f9a4216
Create Date: 2024-06-05 18:28:26.864974

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5054d9881e4'
down_revision = '96f23f9a4216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'moving_objects',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('mjd', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('ra', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('dec', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('ra_err', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('dec_err', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_moving_objects_created_at'),
        'moving_objects',
        ['created_at'],
        unique=False,
    )
    op.create_table(
        'moving_object_associations',
        sa.Column('moving_object_id', sa.String(), nullable=False),
        sa.Column('obj_id', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['moving_object_id'], ['moving_objects.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['obj_id'], ['objs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('moving_object_id', 'obj_id', 'id'),
    )
    op.create_index(
        op.f('ix_moving_object_associations_created_at'),
        'moving_object_associations',
        ['created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_moving_object_associations_created_at'),
        table_name='moving_object_associations',
    )
    op.drop_table('moving_object_associations')
    op.drop_index(op.f('ix_moving_objects_created_at'), table_name='moving_objects')
    op.drop_table('moving_objects')
    # ### end Alembic commands ###
