"""Observation run duration migration

Revision ID: e54b1c00dabf
Revises: 94f87495c701
Create Date: 2024-07-18 21:33:02.095439

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54b1c00dabf'
down_revision = '94f87495c701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'observingruns',
        sa.Column('duration', sa.Integer(), nullable=True, server_default='1'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observingruns', 'duration')
    # ### end Alembic commands ###
