"""skymaps

Revision ID: e9b7657f6be1
Revises: fb0304aeca6c
Create Date: 2021-06-21 17:56:01.193974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9b7657f6be1'
down_revision = 'fb0304aeca6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gcnevents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('sent_by_id', sa.Integer(), nullable=False),
        sa.Column('dateobs', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('dateobs'),
    )
    op.create_index(
        op.f('ix_gcnevents_created_at'), 'gcnevents', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_gcnevents_sent_by_id'), 'gcnevents', ['sent_by_id'], unique=False
    )
    op.create_table(
        'gcnnotices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('sent_by_id', sa.Integer(), nullable=False),
        sa.Column('ivorn', sa.String(), nullable=True),
        sa.Column(
            'notice_type',
            sa.Enum(
                'GRB_COORDS',
                'TEST_COORDS',
                'IM_ALIVE',
                'KILL_SOCKET',
                'MAXBC',
                'BRAD_COORDS',
                'GRB_FINAL',
                'HUNTS_SRC',
                'ALEXIS_SRC',
                'XTE_PCA_ALERT',
                'XTE_PCA_SRC',
                'XTE_ASM_ALERT',
                'XTE_ASM_SRC',
                'COMPTEL_SRC',
                'IPN_RAW',
                'IPN_SEG',
                'SAX_WFC_ALERT',
                'SAX_WFC_SRC',
                'SAX_NFI_ALERT',
                'SAX_NFI_SRC',
                'XTE_ASM_TRANS',
                'spare38',
                'IPN_POS',
                'HETE_ALERT_SRC',
                'HETE_UPDATE_SRC',
                'HETE_FINAL_SRC',
                'HETE_GNDANA_SRC',
                'HETE_TEST',
                'GRB_CNTRPART',
                'SWIFT_TOO_FOM',
                'SWIFT_TOO_SC_SLEW',
                'DOW_TOD',
                'spare50',
                'INTEGRAL_POINTDIR',
                'INTEGRAL_SPIACS',
                'INTEGRAL_WAKEUP',
                'INTEGRAL_REFINED',
                'INTEGRAL_OFFLINE',
                'INTEGRAL_WEAK',
                'AAVSO',
                'MILAGRO_POS',
                'KONUS_LC',
                'SWIFT_BAT_GRB_ALERT',
                'SWIFT_BAT_GRB_POS_ACK',
                'SWIFT_BAT_GRB_POS_NACK',
                'SWIFT_BAT_GRB_LC',
                'SWIFT_BAT_SCALEDMAP',
                'SWIFT_FOM_OBS',
                'SWIFT_SC_SLEW',
                'SWIFT_XRT_POSITION',
                'SWIFT_XRT_SPECTRUM',
                'SWIFT_XRT_IMAGE',
                'SWIFT_XRT_LC',
                'SWIFT_XRT_CENTROID',
                'SWIFT_UVOT_DBURST',
                'SWIFT_UVOT_FCHART',
                'SWIFT_BAT_GRB_LC_PROC',
                'SWIFT_XRT_SPECTRUM_PROC',
                'SWIFT_XRT_IMAGE_PROC',
                'SWIFT_UVOT_DBURST_PROC',
                'SWIFT_UVOT_FCHART_PROC',
                'SWIFT_UVOT_POS',
                'SWIFT_BAT_GRB_POS_TEST',
                'SWIFT_POINTDIR',
                'SWIFT_BAT_TRANS',
                'SWIFT_XRT_THRESHPIX',
                'SWIFT_XRT_THRESHPIX_PROC',
                'SWIFT_XRT_SPER',
                'SWIFT_XRT_SPER_PROC',
                'SWIFT_UVOT_POS_NACK',
                'SWIFT_BAT_ALARM_SHORT',
                'SWIFT_BAT_ALARM_LONG',
                'SWIFT_UVOT_EMERGENCY',
                'SWIFT_XRT_EMERGENCY',
                'SWIFT_FOM_PPT_ARG_ERR',
                'SWIFT_FOM_SAFE_POINT',
                'SWIFT_FOM_SLEW_ABORT',
                'SWIFT_BAT_QL_POS',
                'SWIFT_BAT_SUB_THRESHOLD',
                'SWIFT_BAT_SLEW_POS',
                'AGILE_GRB_WAKEUP',
                'AGILE_GRB_GROUND',
                'AGILE_GRB_REFINED',
                'SWIFT_ACTUAL_POINTDIR',
                'AGILE_MCAL_ALERT',
                'AGILE_POINTDIR',
                'AGILE_TRANS',
                'AGILE_GRB_POS_TEST',
                'FERMI_GBM_ALERT',
                'FERMI_GBM_FLT_POS',
                'FERMI_GBM_GND_POS',
                'FERMI_GBM_LC',
                'FERMI_GBM_GND_INTERNAL',
                'FERMI_GBM_FIN_POS',
                'FERMI_GBM_ALERT_INTERNAL',
                'FERMI_GBM_FLT_INTERNAL',
                'FERMI_GBM_TRANS',
                'FERMI_GBM_POS_TEST',
                'FERMI_LAT_POS_INI',
                'FERMI_LAT_POS_UPD',
                'FERMI_LAT_POS_DIAG',
                'FERMI_LAT_TRANS',
                'FERMI_LAT_POS_TEST',
                'FERMI_LAT_MONITOR',
                'FERMI_SC_SLEW',
                'FERMI_LAT_GND',
                'FERMI_LAT_OFFLINE',
                'FERMI_POINTDIR',
                'SIMBADNED',
                'FERMI_GBM_SUBTHRESH',
                'SWIFT_BAT_MONITOR',
                'MAXI_UNKNOWN',
                'MAXI_KNOWN',
                'MAXI_TEST',
                'OGLE',
                'CBAT',
                'MOA',
                'SWIFT_BAT_SUBSUB',
                'SWIFT_BAT_KNOWN_SRC',
                'VOE_11_IM_ALIVE',
                'VOE_20_IM_ALIVE',
                'FERMI_SC_SLEW_INTERNAL',
                'COINCIDENCE',
                'FERMI_GBM_FIN_INTERNAL',
                'SUZAKU_LC',
                'SNEWS',
                'LVC_PRELIMINARY',
                'LVC_INITIAL',
                'LVC_UPDATE',
                'LVC_TEST',
                'LVC_COUNTERPART',
                'AMON_ICECUBE_COINC',
                'AMON_ICECUBE_HESE',
                'CALET_GBM_FLT_LC',
                'CALET_GBM_GND_LC',
                'LVC_EARLY_WARNING',
                'LVC_RETRACTION',
                'GWHEN_COINC',
                'AMON_ICECUBE_EHE',
                'HAWC_BURST_MONITOR',
                'AMON_NU_EM_COINC',
                'ICECUBE_ASTROTRACK_GOLD',
                'ICECUBE_ASTROTRACK_BRONZE',
                'ICECUBE_CASCADE',
                name='noticetype',
            ),
            nullable=False,
        ),
        sa.Column('stream', sa.String(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('dateobs', sa.DateTime(), nullable=False),
        sa.Column('content', sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(['dateobs'], ['gcnevents.dateobs'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_gcnnotices_created_at'), 'gcnnotices', ['created_at'], unique=False
    )
    op.create_index(op.f('ix_gcnnotices_ivorn'), 'gcnnotices', ['ivorn'], unique=True)
    op.create_index(
        op.f('ix_gcnnotices_sent_by_id'), 'gcnnotices', ['sent_by_id'], unique=False
    )
    op.create_table(
        'gcntags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('sent_by_id', sa.Integer(), nullable=False),
        sa.Column('dateobs', sa.DateTime(), nullable=False),
        sa.Column('text', sa.Unicode(), nullable=False),
        sa.ForeignKeyConstraint(['dateobs'], ['gcnevents.dateobs'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_gcntags_created_at'), 'gcntags', ['created_at'], unique=False
    )
    op.create_index(op.f('ix_gcntags_dateobs'), 'gcntags', ['dateobs'], unique=False)
    op.create_index(
        op.f('ix_gcntags_sent_by_id'), 'gcntags', ['sent_by_id'], unique=False
    )
    op.create_table(
        'localizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('sent_by_id', sa.Integer(), nullable=False),
        sa.Column('dateobs', sa.DateTime(), nullable=False),
        sa.Column('localization_name', sa.String(), nullable=True),
        sa.Column('uniq', sa.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column('probdensity', sa.ARRAY(sa.Float()), nullable=False),
        sa.Column('distmu', sa.ARRAY(sa.Float()), nullable=True),
        sa.Column('distsigma', sa.ARRAY(sa.Float()), nullable=True),
        sa.Column('distnorm', sa.ARRAY(sa.Float()), nullable=True),
        sa.Column('contour', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['dateobs'], ['gcnevents.dateobs'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_localizations_created_at'),
        'localizations',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_localizations_dateobs'), 'localizations', ['dateobs'], unique=False
    )
    op.create_index(
        op.f('ix_localizations_localization_name'),
        'localizations',
        ['localization_name'],
        unique=False,
    )
    op.create_index(
        op.f('ix_localizations_sent_by_id'),
        'localizations',
        ['sent_by_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_localizations_sent_by_id'), table_name='localizations')
    op.drop_index(
        op.f('ix_localizations_localization_name'), table_name='localizations'
    )
    op.drop_index(op.f('ix_localizations_dateobs'), table_name='localizations')
    op.drop_index(op.f('ix_localizations_created_at'), table_name='localizations')
    op.drop_table('localizations')
    op.drop_index(op.f('ix_gcntags_sent_by_id'), table_name='gcntags')
    op.drop_index(op.f('ix_gcntags_dateobs'), table_name='gcntags')
    op.drop_index(op.f('ix_gcntags_created_at'), table_name='gcntags')
    op.drop_table('gcntags')
    op.drop_index(op.f('ix_gcnnotices_sent_by_id'), table_name='gcnnotices')
    op.drop_index(op.f('ix_gcnnotices_ivorn'), table_name='gcnnotices')
    op.drop_index(op.f('ix_gcnnotices_created_at'), table_name='gcnnotices')
    op.drop_table('gcnnotices')
    op.drop_index(op.f('ix_gcnevents_sent_by_id'), table_name='gcnevents')
    op.drop_index(op.f('ix_gcnevents_created_at'), table_name='gcnevents')
    op.drop_table('gcnevents')
    # ### end Alembic commands ###
