"""Add color to source tags

Revision ID: ea81408358d4
Revises: 6f853af1e900
Create Date: 2025-06-26 11:02:42.645118

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "ea81408358d4"
down_revision = "6f853af1e900"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("objtagoptions", sa.Column("color", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objtagoptions", "color")
    # ### end Alembic commands ###
