"""Source scanning / classification voting migration

Revision ID: eb9b9ff111bf
Revises: fddf75137a30
Create Date: 2022-12-17 21:27:32.368769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9b9ff111bf'
down_revision = 'fddf75137a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sourcescans',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('obj_id', sa.String(), nullable=False),
        sa.Column('scanner_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['obj_id'], ['objs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['scanner_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_sourcescans_created_at'), 'sourcescans', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_sourcescans_group_id'), 'sourcescans', ['group_id'], unique=False
    )
    op.create_index(
        op.f('ix_sourcescans_obj_id'), 'sourcescans', ['obj_id'], unique=False
    )
    op.create_index(
        op.f('ix_sourcescans_scanner_id'), 'sourcescans', ['scanner_id'], unique=False
    )
    op.create_table(
        'classificationvotes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('classification_id', sa.Integer(), nullable=False),
        sa.Column('voter_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('vote', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['classification_id'], ['classifications.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_classificationvotes_classification_id'),
        'classificationvotes',
        ['classification_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_classificationvotes_created_at'),
        'classificationvotes',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_classificationvotes_vote'),
        'classificationvotes',
        ['vote'],
        unique=False,
    )
    op.create_index(
        op.f('ix_classificationvotes_voter_id'),
        'classificationvotes',
        ['voter_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_classificationvotes_voter_id'), table_name='classificationvotes'
    )
    op.drop_index(op.f('ix_classificationvotes_vote'), table_name='classificationvotes')
    op.drop_index(
        op.f('ix_classificationvotes_created_at'), table_name='classificationvotes'
    )
    op.drop_index(
        op.f('ix_classificationvotes_classification_id'),
        table_name='classificationvotes',
    )
    op.drop_table('classificationvotes')
    op.drop_index(op.f('ix_sourcescans_scanner_id'), table_name='sourcescans')
    op.drop_index(op.f('ix_sourcescans_obj_id'), table_name='sourcescans')
    op.drop_index(op.f('ix_sourcescans_group_id'), table_name='sourcescans')
    op.drop_index(op.f('ix_sourcescans_created_at'), table_name='sourcescans')
    op.drop_table('sourcescans')
    # ### end Alembic commands ###
