"""confirm_reject_sources_in_gcn

Revision ID: ef7f7859dbba
Revises: 556169569def
Create Date: 2022-07-25 12:37:36.280371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7f7859dbba'
down_revision = '556169569def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sourcesconfirmedingcns',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('obj_id', sa.String(), nullable=False),
        sa.Column('dateobs', sa.DateTime(), nullable=False),
        sa.Column('confirmed', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['dateobs'], ['gcnevents.dateobs'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['obj_id'], ['objs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_sourcesconfirmedingcns_created_at'),
        'sourcesconfirmedingcns',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_sourcesconfirmedingcns_dateobs'),
        'sourcesconfirmedingcns',
        ['dateobs'],
        unique=False,
    )
    op.create_index(
        op.f('ix_sourcesconfirmedingcns_obj_id'),
        'sourcesconfirmedingcns',
        ['obj_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_sourcesconfirmedingcns_obj_id'),
        table_name='sourcesconfirmedingcns',
    )
    op.drop_index(
        op.f('ix_sourcesconfirmedingcns_dateobs'),
        table_name='sourcesconfirmedingcns',
    )
    op.drop_index(
        op.f('ix_sourcesconfirmedingcns_created_at'),
        table_name='sourcesconfirmedingcns',
    )
    op.drop_table('sourcesconfirmedingcns')
    # ### end Alembic commands ###
