"""confirm_reject_sources_in_gcn

Revision ID: ef7f7859dbba
Revises: 556169569def
Create Date: 2022-07-25 12:37:36.280371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7f7859dbba'
down_revision = '556169569def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sourcesingcns',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('obj_id', sa.String(), nullable=False),
        sa.Column('dateobs', sa.DateTime(), nullable=False),
        sa.Column('confirmed_or_rejected', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['dateobs'], ['gcnevents.dateobs'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['obj_id'], ['objs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_sourcesingcns_created_at'),
        'sourcesingcns',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_sourcesingcns_dateobs'), 'sourcesingcns', ['dateobs'], unique=False
    )
    op.create_index(
        op.f('ix_sourcesingcns_obj_id'), 'sourcesingcns', ['obj_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sourcesingcns_obj_id'), table_name='sourcesingcns')
    op.drop_index(op.f('ix_sourcesingcns_dateobs'), table_name='sourcesingcns')
    op.drop_index(op.f('ix_sourcesingcns_created_at'), table_name='sourcesingcns')
    op.drop_table('sourcesingcns')
    # ### end Alembic commands ###
