"""shift replacement

Revision ID: ef9de60f0207
Revises: 8ec1cf68e06f
Create Date: 2022-05-13 23:00:51.990374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9de60f0207'
down_revision = '8ec1cf68e06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'shift_users', sa.Column('needs_replacement', sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_users', 'needs_replacement')
    # ### end Alembic commands ###
