"""ephemeris caching

Revision ID: f222c865fc3a
Revises: 93d1e086aafb
Create Date: 2020-10-23 14:13:43.757346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f222c865fc3a'
down_revision = '93d1e086aafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'classicalassignments',
        sa.Column('rise_time_utc', sa.DateTime(), nullable=False),
    )
    op.add_column(
        'classicalassignments', sa.Column('set_time_utc', sa.DateTime(), nullable=False)
    )
    op.add_column(
        'observingruns',
        sa.Column('ephemeris', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observingruns', 'ephemeris')
    op.drop_column('classicalassignments', 'set_time_utc')
    op.drop_column('classicalassignments', 'rise_time_utc')
    # ### end Alembic commands ###
