"""add magnitude and exposure time columns to the instrument table

Revision ID: f492e8ed9d84
Revises: f9611048498a
Create Date: 2022-01-27 10:06:33.987883

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f492e8ed9d84'
down_revision = 'f9611048498a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('mag', sa.Float(), nullable=True))
    op.add_column('instruments', sa.Column('exposure_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'exposure_time')
    op.drop_column('instruments', 'mag')
