"""Test migration

Revision ID: 5df4b399aae2
Revises: 486c860564a2
Create Date: 2022-03-17 11:41:30.500797

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "5df4b399aae2"
down_revision = "486c860564a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add filters from sncosmo 2.7.0 in the right place
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'atlasc' AFTER 'ps1::w'"
        )
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'atlaso' AFTER 'atlasc'"
        )

        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS '2massj' AFTER 'atlaso'"
        )
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS '2massh' AFTER '2massj'"
        )
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS '2massks' AFTER '2massh'"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
