"""Test migration

Revision ID: f7c1e785d7a4
Revises: 8c48c49f057f
Create Date: 2022-01-13 01:58:56.583337

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f7c1e785d7a4'
down_revision = '8c48c49f057f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tokens_name_key', 'tokens', type_='unique')
    op.create_unique_constraint(
        'token_name_userid_unique_constraint', 'tokens', ['created_by_id', 'name']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_name_userid_unique_constraint', 'tokens', type_='unique')
    op.create_unique_constraint('tokens_name_key', 'tokens', ['name'])
    # ### end Alembic commands ###
