"""Modify token unique constraint to (created_by_id, name); also include leftover enum migration

Revision ID: f7c1e785d7a4
Revises: 8c48c49f057f
Create Date: 2022-01-13 01:58:56.583337

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "f7c1e785d7a4"
down_revision = "8c48c49f057f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tokens_name_key", "tokens", type_="unique")
    op.create_unique_constraint(
        "token_name_userid_unique_constraint", "tokens", ["created_by_id", "name"]
    )
    # ### end Alembic commands ###
    op.execute(
        'ALTER TYPE "public"."followup_apis" RENAME TO "followup_apis__old_version_to_be_dropped"'
    )
    op.execute(
        """CREATE TYPE "public"."followup_apis" AS ENUM ('KAITAPI', 'SEDMAPI', 'SEDMV2API', 'IOOAPI', 'IOIAPI', 'SPRATAPI', 'SINISTROAPI', 'SPECTRALAPI', 'FLOYDSAPI', 'MUSCATAPI', 'ZTFAPI')"""
    )
    op.execute(
        'ALTER TABLE "public"."instruments" ALTER COLUMN api_classname TYPE "public"."followup_apis" USING api_classname::text::"public"."followup_apis"'
    )
    op.execute('DROP TYPE "public"."followup_apis__old_version_to_be_dropped"')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("token_name_userid_unique_constraint", "tokens", type_="unique")
    op.create_unique_constraint("tokens_name_key", "tokens", ["name"])
    # ### end Alembic commands ###
    op.execute(
        'ALTER TYPE "public"."followup_apis" RENAME TO "followup_apis__new_version_to_be_dropped"'
    )
    op.execute(
        """CREATE TYPE "public"."followup_apis" AS ENUM ('SEDMAPI', 'IOOAPI', 'IOIAPI', 'SPRATAPI', 'SINISTROAPI', 'SPECTRALAPI', 'FLOYDSAPI', 'MUSCATAPI')"""
    )
    op.execute(
        'ALTER TABLE "public"."instruments" ALTER COLUMN api_classname TYPE "public"."followup_apis" USING api_classname::text::"public"."followup_apis"'
    )
    op.execute('DROP TYPE "public"."followup_apis__new_version_to_be_dropped"')
