"""Localization-based notifications migration

Revision ID: fa832ea0ee8d
Revises: 99c470d77682
Create Date: 2023-01-17 23:03:50.327815

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fa832ea0ee8d"
down_revision = "99c470d77682"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "defaultobservationplanrequests",
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("defaultobservationplanrequests", "filters")
    # ### end Alembic commands ###
