"""DECam u-band migration

Revision ID: fd92295c50ed
Revises: 06aa146dea7a
Create Date: 2023-05-13 19:14:31.128816

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'fd92295c50ed'
down_revision = '06aa146dea7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE bandpasses ADD VALUE IF NOT EXISTS 'desu' AFTER 'standard::i'"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
