"""localizatintilepartitions

Revision ID: fdab0cc9eb78
Revises: 47a76ff0f3ce
Create Date: 2023-04-19 09:08:38.281780

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'fdab0cc9eb78'
down_revision = '47a76ff0f3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE localizationtiles ADD COLUMN dateobs DATE')
    op.create_index(
        'localizationtile_id_healpix_dateobs_index',
        'localizationtiles',
        ['id', 'healpix', 'dateobs'],
        unique=False,
    )
    op.execute(
        """ALTER TABLE localizationtiles MODIFY
            PARTITION BY RANGE (YEAR(dateobs), MONTH(dateobs))
        """
    )
    op.execute(
        'CREATE TABLE localizationtiles_def PARTITION OF localizationtiles DEFAULT'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2023_04 PARTITION OF localizationtiles FOR VALUES FROM (2023, 4) TO (2023, 5)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2023_05 PARTITION OF localizationtiles FOR VALUES FROM (2023, 5) TO (2023, 6)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2023_06 PARTITION OF localizationtiles FOR VALUES FROM (2023, 6) TO (2023, 7)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2023_07 PARTITION OF localizationtiles FOR VALUES FROM (2023, 7) TO (2023, 8)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2023_08 PARTITION OF localizationtiles FOR VALUES FROM (2023, 8) TO (2023, 9)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2023_09 PARTITION OF localizationtiles FOR VALUES FROM (2023, 9) TO (2023, 10)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2023_10 PARTITION OF localizationtiles FOR VALUES FROM (2023, 10) TO (2023, 11)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2023_11 PARTITION OF localizationtiles FOR VALUES FROM (2023, 11) TO (2023, 12)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2023_12 PARTITION OF localizationtiles FOR VALUES FROM (2023, 12) TO (2024, 1)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_01 PARTITION OF localizationtiles FOR VALUES FROM (2024, 1) TO (2024, 2)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_02 PARTITION OF localizationtiles FOR VALUES FROM (2024, 2) TO (2024, 3)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_03 PARTITION OF localizationtiles FOR VALUES FROM (2024, 3) TO (2024, 4)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_04 PARTITION OF localizationtiles FOR VALUES FROM (2024, 4) TO (2024, 5)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_05 PARTITION OF localizationtiles FOR VALUES FROM (2024, 5) TO (2024, 6)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_06 PARTITION OF localizationtiles FOR VALUES FROM (2024, 6) TO (2024, 7)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_07 PARTITION OF localizationtiles FOR VALUES FROM (2024, 7) TO (2024, 8)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_08 PARTITION OF localizationtiles FOR VALUES FROM (2024, 8) TO (2024, 9)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_09 PARTITION OF localizationtiles FOR VALUES FROM (2024, 9) TO (2024, 10)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_10 PARTITION OF localizationtiles FOR VALUES FROM (2024, 10) TO (2024, 11)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_11 PARTITION OF localizationtiles FOR VALUES FROM (2024, 11) TO (2024, 12)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2024_12 PARTITION OF localizationtiles FOR VALUES FROM (2024, 12) TO (2025, 1)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2025_01 PARTITION OF localizationtiles FOR VALUES FROM (2025, 1) TO (2025, 2)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2025_02 PARTITION OF localizationtiles FOR VALUES FROM (2025, 2) TO (2025, 3)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2025_03 PARTITION OF localizationtiles FOR VALUES FROM (2025, 3) TO (2025, 4)'
    )
    op.execute(
        'CREATE TABLE localizationtiles_2025_04 PARTITION OF localizationtiles FOR VALUES FROM (2025, 4) TO (2025, 5)'
    )
