"""Follow-up request migration

Revision ID: fddf75137a30
Revises: 9f2563d6c9b5
Create Date: 2022-12-11 00:22:33.020951

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fddf75137a30"
down_revision = "9f2563d6c9b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "defaultfollowuprequests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allocation_id", sa.Integer(), nullable=False),
        sa.Column("default_followup_name", sa.String(), nullable=False),
        sa.Column(
            "source_filter", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"], ["allocations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("default_followup_name"),
    )
    op.create_index(
        op.f("ix_defaultfollowuprequests_allocation_id"),
        "defaultfollowuprequests",
        ["allocation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_defaultfollowuprequests_created_at"),
        "defaultfollowuprequests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_defaultfollowuprequests_requester_id"),
        "defaultfollowuprequests",
        ["requester_id"],
        unique=False,
    )
    op.create_table(
        "default_followup_groups",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("defaultfollowuprequest_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["defaultfollowuprequest_id"],
            ["defaultfollowuprequests.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "default_followup_groups_forward_ind",
        "default_followup_groups",
        ["defaultfollowuprequest_id", "group_id"],
        unique=True,
    )
    op.create_index(
        "default_followup_groups_reverse_ind",
        "default_followup_groups",
        ["group_id", "defaultfollowuprequest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_default_followup_groups_created_at"),
        "default_followup_groups",
        ["created_at"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_default_followup_groups_created_at"),
        table_name="default_followup_groups",
    )
    op.drop_index(
        "default_followup_groups_reverse_ind", table_name="default_followup_groups"
    )
    op.drop_index(
        "default_followup_groups_forward_ind", table_name="default_followup_groups"
    )
    op.drop_table("default_followup_groups")
    op.drop_index(
        op.f("ix_defaultfollowuprequests_requester_id"),
        table_name="defaultfollowuprequests",
    )
    op.drop_index(
        op.f("ix_defaultfollowuprequests_created_at"),
        table_name="defaultfollowuprequests",
    )
    op.drop_index(
        op.f("ix_defaultfollowuprequests_allocation_id"),
        table_name="defaultfollowuprequests",
    )
    op.drop_table("defaultfollowuprequests")
    # ### end Alembic commands ###
