"""Executed observations indices migration

Revision ID: ffb23be05fa7
Revises: 97266d7af6e7
Create Date: 2023-05-02 03:30:36.428129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb23be05fa7'
down_revision = '97266d7af6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'executedobservations',
        'instrument_field_id',
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.create_index(
        op.f('ix_executedobservations_instrument_field_id'),
        'executedobservations',
        ['instrument_field_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_executedobservations_instrument_id'),
        'executedobservations',
        ['instrument_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_executedobservations_instrument_id'), table_name='executedobservations'
    )
    op.drop_index(
        op.f('ix_executedobservations_instrument_field_id'),
        table_name='executedobservations',
    )
    op.alter_column(
        'executedobservations',
        'instrument_field_id',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
