"""reference flux

Revision ID: fff290c02ef8
Revises: 4822ff118a4f
Create Date: 2022-09-06 13:37:43.114048

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fff290c02ef8"
down_revision = "44a7408c38a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photometry", sa.Column("ref_flux", sa.Float(), nullable=True))
    op.add_column("photometry", sa.Column("ref_fluxerr", sa.Float(), nullable=True))
    op.create_index(
        op.f("ix_photometry_ref_flux"), "photometry", ["ref_flux"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photometry_ref_flux"), table_name="photometry")
    op.drop_column("photometry", "ref_fluxerr")
    op.drop_column("photometry", "ref_flux")
    # ### end Alembic commands ###
