[program:scout_service]
command=/usr/bin/env python services/scout_service/scout_service.py %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/scout_service.log
redirect_stderr=true
