name: Reusable Cache Save Workflow
inputs:
  key-prefix:
    description: Cache key prefix
    default: "pr"

on:
  workflow_call:

runs:
  using: "composite"
  steps:
    - uses: actions/cache/save@v4
      with:
        path: |
          ~/.npm
        key: ${{ inputs.key-prefix }}-${{ runner.os }}-npm-${{ hashFiles('package.json') }}

    - uses: actions/cache/save@v4
      with:
        path: |
          ~/.cache/pip
        key: ${{ inputs.key-prefix }}-${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

    # caching dustmap & sncosmo files is dependent on their corresponding
    # python package versions, so we use that as the cache key
    - uses: actions/cache/save@v4
      with:
        path: |
          persistentdata/dustmap/sfd
        key: ${{ inputs.key-prefix }}-${{ runner.os }}-dustmap-${{ hashFiles('**/requirements*.txt') }}

    - uses: actions/cache/save@v4
      with:
        path: |
          ~/.astropy/cache/sncosmo/bandpasses
        key: ${{ inputs.key-prefix }}-${{ runner.os }}-sncosmo-${{ hashFiles('**/requirements*.txt') }}
