[program:neofixer_service]
command=/usr/bin/env python services/neofixer_service/neofixer_service.py %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/neofixer_service.log
redirect_stderr=true
