/**
 * Generated by tools/docs/build-route-schema-map.py — DO NOT EDIT.
 *
 * Maps "<METHOD> <path>" → { schema: keyof components["schemas"], list: boolean,
 * wrapper?: string } for the impending RTK-Query spec-typing pass. The optional
 * `wrapper` field is emitted for pagination-wrapper payloads where the response
 * `data` is `{ [wrapper]: <item>[], totalMatches?, pageNumber?, ... }` — see the
 * generator's `_resolve_wrapped_data_member` rule. Endpoints whose data shape is
 * still inline/unknown are omitted (they'll surface as the next gap to tighten).
 */
import type { components } from "./api";

export type SchemaName = keyof components["schemas"];

export const ROUTE_SCHEMA_MAP = {
  "DELETE /api/candidates/{obj_id}": { schema: "Success" as const, list: false },
  "DELETE /api/candidates/{obj_id}/{filter_id}": { schema: "Success" as const, list: false },
  "DELETE /api/earthquake/{earthquake_id}/mmadetector/{mma_detector_id}/measurements": { schema: "Success" as const, list: false },
  "DELETE /api/earthquake/{event_id}": { schema: "Success" as const, list: false },
  "DELETE /api/instrument/{instrument_id}": { schema: "Success" as const, list: false },
  "DELETE /api/instrument/{instrument_id}/fields": { schema: "Success" as const, list: false },
  "DELETE /api/observation_plan/{observation_plan_request_id}/fields": { schema: "ObservationPlanRequest" as const, list: false },
  "DELETE /api/observation_plan/{observation_plan_request_id}/queue": { schema: "SingleObservationPlanRequest" as const, list: false },
  "DELETE /api/photometry/bulk_delete/{upload_id}": { schema: "Success" as const, list: false },
  "DELETE /api/photometry/{photometry_id}": { schema: "Success" as const, list: false },
  "DELETE /api/sources/{obj_id}/photometry": { schema: "Success" as const, list: false },
  "DELETE /api/spectra/{spectrum_id}": { schema: "Success" as const, list: false },
  "DELETE /api/spectrum/{spectrum_id}": { schema: "Success" as const, list: false },
  "GET /api/allocation": { schema: "Allocation" as const, list: true },
  "GET /api/allocation/observation_plans/{allocation_id}": { schema: "ObservationPlanRequest" as const, list: true },
  "GET /api/allocation/{allocation_id}": { schema: "Allocation" as const, list: false, wrapper: "allocation" as const },
  "GET /api/analysis_service": { schema: "AnalysisService" as const, list: true },
  "GET /api/analysis_service/{analysis_service_id}": { schema: "AnalysisService" as const, list: false },
  "GET /api/analysis_service/{analysis_service_id}/default_analysis": { schema: "DefaultAnalysis" as const, list: true },
  "GET /api/analysis_service/{analysis_service_id}/default_analysis/{default_analysis_id}": { schema: "DefaultAnalysis" as const, list: false },
  "GET /api/assignment": { schema: "ClassicalAssignment" as const, list: true },
  "GET /api/assignment/{assignment_id}": { schema: "ClassicalAssignment" as const, list: false },
  "GET /api/candidates/scan_reports": { schema: "ScanReport" as const, list: true },
  "GET /api/candidates/scan_reports/{report_id}/items/{_}": { schema: "ScanReportItem" as const, list: true },
  "GET /api/candidates/{obj_id}": { schema: "Obj" as const, list: false },
  "GET /api/classification": { schema: "Classification" as const, list: true, wrapper: "sources" as const },
  "GET /api/classification/{classification_id}": { schema: "Classification" as const, list: false },
  "GET /api/default_followup_request": { schema: "DefaultFollowupRequest" as const, list: true },
  "GET /api/default_followup_request/{default_followup_request_id}": { schema: "DefaultFollowupRequest" as const, list: false },
  "GET /api/default_gcn_tag": { schema: "DefaultGcnTag" as const, list: true },
  "GET /api/default_gcn_tag/{default_gcn_tag_id}": { schema: "DefaultGcnTag" as const, list: false },
  "GET /api/default_observation_plan": { schema: "DefaultObservationPlanRequest" as const, list: true },
  "GET /api/default_observation_plan/{default_observation_plan_id}": { schema: "DefaultObservationPlanRequest" as const, list: false },
  "GET /api/default_survey_efficiency": { schema: "DefaultSurveyEfficiencyRequest" as const, list: true },
  "GET /api/default_survey_efficiency/{default_survey_efficiency_id}": { schema: "DefaultSurveyEfficiencyRequest" as const, list: false },
  "GET /api/earthquake": { schema: "EarthquakeEvent" as const, list: true, wrapper: "events" as const },
  "GET /api/earthquake/{earthquake_id}/mmadetector/{mma_detector_id}/measurements": { schema: "EarthquakeMeasured" as const, list: false },
  "GET /api/earthquake/{event_id}": { schema: "EarthquakeEvent" as const, list: false },
  "GET /api/filters": { schema: "Filter" as const, list: true },
  "GET /api/filters/{filter_id}": { schema: "Filter" as const, list: false },
  "GET /api/followup_request": { schema: "FollowupRequest" as const, list: true, wrapper: "followup_requests" as const },
  "GET /api/followup_request/{followup_request_id}": { schema: "FollowupRequest" as const, list: false },
  "GET /api/galaxy_catalog/{catalog_name}": { schema: "Galaxy" as const, list: true, wrapper: "galaxies" as const },
  "GET /api/gcn_event": { schema: "GcnEvent" as const, list: true, wrapper: "events" as const },
  "GET /api/gcn_event/properties": { schema: "GcnProperty" as const, list: true },
  "GET /api/gcn_event/{dateobs}": { schema: "GcnEvent" as const, list: false },
  "GET /api/gcn_event/{dateobs}/report/{report_id}": { schema: "GcnReport" as const, list: false },
  "GET /api/gcn_event/{dateobs}/summary/{summary_id}": { schema: "GcnSummary" as const, list: false },
  "GET /api/gcn_event/{gcnevent_id}/catalog_query": { schema: "CatalogQuery" as const, list: true },
  "GET /api/gcn_event/{gcnevent_id}/observation_plan_requests": { schema: "ObservationPlanRequest" as const, list: true },
  "GET /api/gcn_event/{gcnevent_id}/survey_efficiency": { schema: "SurveyEfficiencyForObservations" as const, list: true },
  "GET /api/group_admission_requests": { schema: "GroupAdmissionRequest" as const, list: true },
  "GET /api/group_admission_requests/{admission_request_id}": { schema: "GroupAdmissionRequest" as const, list: false },
  "GET /api/groups/public": { schema: "Group" as const, list: false },
  "GET /api/instrument": { schema: "Instrument" as const, list: true },
  "GET /api/instrument/{instrument_id}": { schema: "Instrument" as const, list: false },
  "GET /api/invitations": { schema: "Invitation" as const, list: true, wrapper: "invitations" as const },
  "GET /api/listing/{user_id}": { schema: "Listing" as const, list: true },
  "GET /api/localization/properties": { schema: "LocalizationProperty" as const, list: true },
  "GET /api/localization/{dateobs}/name/{localization_name}": { schema: "Localization" as const, list: false },
  "GET /api/mmadetector": { schema: "MMADetector" as const, list: true },
  "GET /api/mmadetector/spectra/{spectrum_id}": { schema: "MMADetectorSpectrum" as const, list: false },
  "GET /api/mmadetector/time_intervals/{time_interval_id}": { schema: "MMADetectorTimeInterval" as const, list: false },
  "GET /api/mmadetector/{mmadetector_id}": { schema: "MMADetector" as const, list: false },
  "GET /api/objtag": { schema: "ObjTag" as const, list: true },
  "GET /api/objtagoption": { schema: "ObjTagOption" as const, list: true },
  "GET /api/observation": { schema: "ExecutedObservation" as const, list: true },
  "GET /api/observation/external_api/{allocation_id}": { schema: "PlannedObservation" as const, list: true },
  "GET /api/observation_plan": { schema: "ObservationPlanRequest" as const, list: true, wrapper: "requests" as const },
  "GET /api/observation_plan/{observation_plan_request_id}": { schema: "ObservationPlanRequest" as const, list: false },
  "GET /api/observation_plan/{observation_plan_request_id}/gcn": { schema: "ObservationPlanRequest" as const, list: false },
  "GET /api/observation_plan/{observation_plan_request_id}/geojson": { schema: "ObservationPlanRequest" as const, list: false },
  "GET /api/observation_plan/{observation_plan_request_id}/movie": { schema: "ObservationPlanRequest" as const, list: false },
  "GET /api/observation_plan/{observation_plan_request_id}/survey_efficiency": { schema: "SurveyEfficiencyForObservationPlan" as const, list: true },
  "GET /api/observing_run": { schema: "ObservingRun" as const, list: true },
  "GET /api/observing_run/{run_id}": { schema: "ObservingRunGetWithAssignments" as const, list: false },
  "GET /api/photometric_series": { schema: "PhotometricSeries" as const, list: true, wrapper: "series" as const },
  "GET /api/public_pages/release": { schema: "PublicRelease" as const, list: true },
  "GET /api/public_pages/source/{source_id}": { schema: "PublicSourcePage" as const, list: true },
  "GET /api/recurring_api": { schema: "RecurringAPI" as const, list: true },
  "GET /api/recurring_api/{recurring_api_id}": { schema: "RecurringAPI" as const, list: false },
  "GET /api/roles": { schema: "Role" as const, list: true },
  "GET /api/sharing_service": { schema: "SharingService" as const, list: true },
  "GET /api/sharing_service/submission": { schema: "SharingServiceSubmission" as const, list: true, wrapper: "submissions" as const },
  "GET /api/sharing_service/submission/{sharing_service_submission_id}": { schema: "SharingServiceSubmission" as const, list: false },
  "GET /api/sharing_service/{sharing_service_id}": { schema: "SharingService" as const, list: false },
  "GET /api/shifts": { schema: "Shift" as const, list: true },
  "GET /api/shifts/{shift_id}": { schema: "Shift" as const, list: false },
  "GET /api/skymap_trigger/{allocation_id}": { schema: "PlannedObservation" as const, list: true },
  "GET /api/sources": { schema: "Obj" as const, list: true, wrapper: "sources" as const },
  "GET /api/sources/{obj_id}": { schema: "Obj" as const, list: false },
  "GET /api/sources/{obj_id}/classifications": { schema: "Classification" as const, list: true },
  "GET /api/sources/{obj_id}/groups": { schema: "Group" as const, list: true },
  "GET /api/sources/{obj_id}/phot_stat": { schema: "PhotStat" as const, list: false },
  "GET /api/spatial_catalog": { schema: "SpatialCatalog" as const, list: true },
  "GET /api/spatial_catalog/{catalog_id}": { schema: "SpatialCatalog" as const, list: false },
  "GET /api/spectra": { schema: "Spectrum" as const, list: true },
  "GET /api/spectra/{spectrum_id}": { schema: "Spectrum" as const, list: false },
  "GET /api/spectrum": { schema: "Spectrum" as const, list: true },
  "GET /api/spectrum/{spectrum_id}": { schema: "Spectrum" as const, list: false },
  "GET /api/streams": { schema: "Stream" as const, list: true },
  "GET /api/streams/{stream_id}": { schema: "Stream" as const, list: false },
  "GET /api/survey_efficiency/observation_plan": { schema: "SurveyEfficiencyForObservationPlan" as const, list: true },
  "GET /api/survey_efficiency/observation_plan/{survey_efficiency_analysis_id}": { schema: "SurveyEfficiencyForObservationPlan" as const, list: false },
  "GET /api/survey_efficiency/observations": { schema: "SurveyEfficiencyForObservations" as const, list: true },
  "GET /api/survey_efficiency/observations/{survey_efficiency_analysis_id}": { schema: "SurveyEfficiencyForObservations" as const, list: false },
  "GET /api/taxonomy": { schema: "Taxonomy" as const, list: true },
  "GET /api/taxonomy/{taxonomy_id}": { schema: "Taxonomy" as const, list: false },
  "GET /api/telescope": { schema: "Telescope" as const, list: true },
  "GET /api/telescope/{telescope_id}": { schema: "Telescope" as const, list: false },
  "GET /api/thumbnail/{thumbnail_id}": { schema: "Thumbnail" as const, list: false },
  "GET /api/user": { schema: "User" as const, list: true, wrapper: "users" as const },
  "GET /api/user/{user_id}": { schema: "User" as const, list: false },
  "GET /api/{analysis_resource_type}/analysis": { schema: "ObjAnalysisDetail" as const, list: true },
  "GET /api/{analysis_resource_type}/analysis/{analysis_id}": { schema: "ObjAnalysisDetail" as const, list: false },
  "GET /api/{analysis_resource_type}/{analysis_id}": { schema: "ObjAnalysisDetail" as const, list: true },
  "GET /api/{analysis_resource_type}/{analysis_id}/analysis": { schema: "ObjAnalysisDetail" as const, list: false },
  "GET /api/{associated_resource_type}/{resource_id}": { schema: "Annotation" as const, list: true },
  "GET /api/{associated_resource_type}/{resource_id}/annotations": { schema: "Annotation" as const, list: true },
  "GET /api/{associated_resource_type}/{resource_id}/annotations/{annotation_id}": { schema: "Annotation" as const, list: false },
  "GET /api/{associated_resource_type}/{resource_id}/comments": { schema: "Comment" as const, list: true },
  "GET /api/{associated_resource_type}/{resource_id}/comments/{comment_id}": { schema: "Comment" as const, list: false },
  "GET /api/{associated_resource_type}/{resource_id}/reminders": { schema: "Reminder" as const, list: true },
  "GET /api/{associated_resource_type}/{resource_id}/reminders/{reminder_id}": { schema: "Reminder" as const, list: false },
  "PATCH /api/candidates/scan_reports/{report_id}/items/{item_id}": { schema: "ScanReportItem" as const, list: false },
  "PATCH /api/earthquake/{earthquake_id}/mmadetector/{mma_detector_id}/measurements": { schema: "EarthquakeMeasured" as const, list: false },
  "PATCH /api/groups/{group_id}/users": { schema: "GroupUser" as const, list: false },
  "PATCH /api/mmadetector/spectra/{spectrum_id}": { schema: "MMADetectorSpectrum" as const, list: false },
  "PATCH /api/mmadetector/time_intervals/{time_interval_id}": { schema: "MMADetectorTimeInterval" as const, list: false },
  "PATCH /api/mmadetector/{mmadetector_id}": { schema: "MMADetector" as const, list: false },
  "PATCH /api/photometry/{photometry_id}": { schema: "Success" as const, list: false },
  "PATCH /api/shifts/{shift_id}": { schema: "Shift" as const, list: false },
  "PATCH /api/shifts/{shift_id}/users/{user_id}": { schema: "ShiftUser" as const, list: false },
  "PATCH /api/sources/{obj_id}": { schema: "Obj" as const, list: false },
  "PATCH /api/streams/{stream_id}": { schema: "Stream" as const, list: false },
  "POST /api/candidates/scan_reports": { schema: "ScanReport" as const, list: false },
  "POST /api/earthquake/{earthquake_id}/mmadetector/{mma_detector_id}/measurements": { schema: "EarthquakeMeasured" as const, list: false },
  "POST /api/earthquake/{earthquake_id}/mmadetector/{mma_detector_id}/predictions": { schema: "EarthquakePrediction" as const, list: false },
  "POST /api/galaxy_catalog/ascii": { schema: "Galaxy" as const, list: true },
  "POST /api/groups/{group_id}/usersFromGroups": { schema: "GroupUser" as const, list: false },
  "POST /api/objtag": { schema: "ObjTag" as const, list: false },
  "POST /api/objtagoption": { schema: "ObjTagOption" as const, list: false },
  "POST /api/observation/ascii": { schema: "ExecutedObservation" as const, list: true },
  "POST /api/observation/external_api": { schema: "ExecutedObservation" as const, list: true },
  "POST /api/observation_plan/{observation_plan_request_id}/queue": { schema: "ObservationPlanRequest" as const, list: false },
  "POST /api/sharing_service/submission": { schema: "SharingServiceSubmission" as const, list: false },
  "POST /api/sharing_service/{sharing_service_id}/coauthor/{user_id}": { schema: "SharingServiceCoauthor" as const, list: false },
  "POST /api/sharing_service/{sharing_service_id}/group/{group_id}/auto_publisher/{user_id}": { schema: "SharingServiceGroupAutoPublisher" as const, list: false },
  "POST /api/sources/{obj_id}/annotations/gaia": { schema: "Annotation" as const, list: false },
  "POST /api/sources/{obj_id}/annotations/irsa": { schema: "Annotation" as const, list: false },
  "POST /api/sources/{obj_id}/annotations/ps1": { schema: "Annotation" as const, list: false },
  "POST /api/sources/{obj_id}/annotations/vizier": { schema: "Annotation" as const, list: false },
  "POST /api/spectra/parse/ascii": { schema: "SpectrumNoID" as const, list: false },
  "POST /api/spectra/synthphot/{spectrum_id}": { schema: "Spectrum" as const, list: false },
  "POST /api/spectrum/parse/ascii": { schema: "SpectrumNoID" as const, list: false },
  "POST /api/summary_query": { schema: "Obj" as const, list: true },
  "PUT /api/followup_request/prioritization": { schema: "FollowupRequest" as const, list: false },
  "PUT /api/followup_request/{followup_request_id}/comment": { schema: "FollowupRequest" as const, list: false },
  "PUT /api/followup_request/{request_id}": { schema: "FollowupRequest" as const, list: false },
  "PUT /api/groups/{group_id}": { schema: "Group" as const, list: false },
  "PUT /api/instrument/{instrument_id}": { schema: "Instrument" as const, list: false },
  "PUT /api/observing_run/{run_id}": { schema: "ObservingRun" as const, list: false },
  "PUT /api/sharing_service/{sharing_service_id}/group/{group_id}": { schema: "SharingServiceGroup" as const, list: false },
  "PUT /api/spectra/{spectrum_id}": { schema: "Spectrum" as const, list: false },
  "PUT /api/spectrum/{spectrum_id}": { schema: "Spectrum" as const, list: false },
  "PUT /api/thumbnail/{thumbnail_id}": { schema: "Thumbnail" as const, list: false },
  "PUT /api/{associated_resource_type}/{resource_id}/comments": { schema: "Comment" as const, list: false },
  "PUT /api/{associated_resource_type}/{resource_id}/comments/{comment_id}": { schema: "Comment" as const, list: false },
} satisfies Record<string, { schema: SchemaName; list: boolean; wrapper?: string }>;

type RouteKey = keyof typeof ROUTE_SCHEMA_MAP;
type RouteEntry<P extends RouteKey> = (typeof ROUTE_SCHEMA_MAP)[P];

/**
 * Best-effort optional pagination metadata that ships alongside a wrapper key.
 * Real responses vary (some routes also return `geojson`, `sortBy`, `sortOrder`,
 * `field_ids`, `probability`, ...) — consumers needing those must use `?.`
 * access, since they're not encoded here.
 */
type PaginationBonusFields = {
  totalMatches?: number;
  pageNumber?: number;
  numPerPage?: number;
  page?: number;
};

/**
 * Resolve a route key to the typed shape of its response `data` field.
 * - Pagination-wrapper routes (`wrapper` set) → `{ [W]: Schema[] } & PaginationBonusFields`.
 * - Otherwise the map's `list` flag picks scalar-vs-array automatically.
 *
 * Caveat: PaginationBonusFields makes `totalMatches`/`pageNumber`/`numPerPage`/`page`
 * optional. Routes that historically declared these as required will need `?.`
 * access (or non-null assertions where the value is known to be present).
 *
 * @example
 *   const data: RouteData<"GET /api/allocation"> = ...; // Allocation[]
 *   const evts: RouteData<"GET /api/earthquake"> = ...; // { events: EarthquakeEvent[] } & PaginationBonusFields
 */
export type RouteData<P extends RouteKey> =
  RouteEntry<P> extends { wrapper: infer W extends string; schema: infer S extends SchemaName }
    ? { [K in W]: components["schemas"][S][] } & PaginationBonusFields
    : RouteEntry<P>["list"] extends true
      ? components["schemas"][RouteEntry<P>["schema"]][]
      : components["schemas"][RouteEntry<P>["schema"]];
