name: Reusable Cache Workflow

on:
  workflow_call:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('package.json') }}
            ${{ runner.os }}-npm-

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
            ${{ runner.os }}-pip-

      # caching dustmap & sncosmo files is dependent on their corresponding
      # python package versions, so we use that as the cache key
      - uses: actions/cache@v4
        with:
          path: |
            persistentdata/dustmap/sfd
          key: ${{ runner.os }}-dustmap-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-dustmap-${{ hashFiles('**/requirements*.txt') }}
            ${{ runner.os }}-dustmap-

      - uses: actions/cache@v4
        with:
          path: |
            ~/.astropy/cache/sncosmo/bandpasses
          key: ${{ runner.os }}-sncosmo-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-sncosmo-${{ hashFiles('**/requirements*.txt') }}
            ${{ runner.os }}-sncosmo-
