[program:analysis_rerun]
command=/usr/bin/env python services/analysis_rerun/analysis_rerun.py %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/analysis_rerun.log
redirect_stderr=true
